### ISSUE TITLE
Slow builtins with OpenMP

### ISSUE THREAD

**Issue by FabioLuporini** [devitocodes/devito#1018]
Builtins performing a reduction (e.g., `norm`) are currently insanely slow. This is because an increment is performed at every loop iteration and guarded by a `#pragma atomic` . Instead, we should use a proper OpenMP `reduction` clause

**Comment by FabioLuporini** [comment]
@mloubout this is probably affecting CI too

**Comment by mloubout** [comment]
We only do norms on `rec` which is tiny so I don't think impacts CI that much, can make a pass another PR to remove all of it and see

**Comment by FabioLuporini** [comment]
But it's at least affecting CI due to the redundant codegens and compiles
We are also using `norm` in the MPI tests, even over TimeFunctions

Don't bother doing a pass -- I think I should just fix this once and for all. And we should also sort out the redundant codegens/compiles once and for all

**Comment by FabioLuporini** [comment]
and btw, this is beyond CI

**Comment by FabioLuporini** [comment]
this is now fixed by #1124
