### ISSUE TITLE
CI/DevOps Meta issue

### ISSUE THREAD

**Issue by navjotk** [devitocodes/devito#1045]
Detailed issues can be linked to from this one. 

- Performance regression
- Automate Deployment to PyPI (GitHub actions)
- Automate docs deployment (Github actions)
- A GPU build

More?

**Comment by FabioLuporini** [comment]
* a GPU build ?

**Comment by navjotk** [comment]
Do we have any tests for GPU yet?

**Comment by FabioLuporini** [comment]
only minor codegen tests: https://github.com/devitocodes/devito/blob/move-tiling/tests/test_dle.py#L492

but already having a build with a trivial test with the classic `Operator(Eq(u.forward, u + 1))` running would be great

**Comment by ggorman** [comment]
- testing on windows
- testing on mac

**Comment by ggorman** [comment]
Re-engineering of current testing (travis and pipelines) to use github actions + pipelines.
- What is the list of action and when should they be triggered - eg flake8 can be run on every branch for every commit while deployment of docs only happens on a release.
- Identify dependency between actions. Maximise concurrency - minimise turnaround time.

**Comment by ggorman** [comment]
Perhaps we need to move this to projects.

**Comment by ggorman** [comment]
Closing this as individual issues have ready been created in its place.
