### ISSUE TITLE
Add Action: core pytest, on push to any branch 

### ISSUE THREAD

**Issue by EdCaunt** [devitocodes/devito#1053]

**Comment by navjotk** [comment]
@mloubout what parts of this are you working on? Shall we split the issue into Linux/Mac/Windows?

**Comment by navjotk** [comment]
@BlockSprintZIf would also like to contribute

**Comment by mloubout** [comment]
I'm making the ops/yask/core on linux, almost  done will PR soon

**Comment by navjotk** [comment]
@BlockSprintZIf doing this for Mac

**Comment by mloubout** [comment]
Mac done in #1070 , windows 10 not sure what the plan is
