### ISSUE TITLE
Add action: runner to execute GPU tests on azure, on push to PR

### ISSUE THREAD

**Issue by EdCaunt** [devitocodes/devito#1056]

**Comment by jemrobinson** [comment]
I've written a github action (in progress) here https://github.com/ResearchSoftwareActions/azure-vm-deploy which deploys a VM to Azure. I've got a fork of this repo where I'm testing out using it here (https://github.com/jemrobinson/devito)

**Comment by FabioLuporini** [comment]
action added by #1131 

TODOs in #1137
