### ISSUE TITLE
Add action: deploy to pipy, on release

### ISSUE THREAD

**Issue by EdCaunt** [devitocodes/devito#1058]

**Comment by mloubout** [comment]
Shouldn't this be only for new versions, not for each new PR.

**Comment by navjotk** [comment]
Says in the issue title: "On Release"

**Comment by mloubout** [comment]
Leaving open until next release to be sure it works.

**Comment by FabioLuporini** [comment]
@navjotk how did it go?

**Comment by mloubout** [comment]
This didn't work last release, not sure how to debug it.

**Comment by ggorman** [comment]
Deploying manually I find:

HTTPError: 400 Client Error: Invalid value for requires_dist. Error: Can't have direct dependency: 'cgen @ git+https://github.com/inducer/cgen@master' for url: https://test.pypi.org/legacy/

**Comment by ggorman** [comment]
This is a known issue: https://github.com/pypa/pip/issues/6301

**Comment by ggorman** [comment]
PR fix - https://github.com/devitocodes/devito/pull/1266

**Comment by ggorman** [comment]
Fixed for v4.2.1 release
