### ISSUE TITLE
Add action: test tutorials, on push to any PR

### ISSUE THREAD

**Issue by EdCaunt** [devitocodes/devito#1059]

**Comment by navjotk** [comment]
Notebooks are located in:

https://github.com/devitocodes/devito/tree/master/examples/cfd

https://github.com/devitocodes/devito/tree/master/examples/compiler

https://github.com/devitocodes/devito/blob/master/examples/mpi/overview.ipynb

https://github.com/devitocodes/devito/tree/master/examples/seismic/tutorials

https://github.com/devitocodes/devito/tree/master/examples/userapi
