### ISSUE TITLE
Intro to symbolic computation with Devito

### ISSUE THREAD

**Issue by rhodrin** [devitocodes/devito#1093]
We need a tutorial introducing users to the basics and workflow of Devito. This tutorial will also serve as part of the introduction at workshops such as OGHPC.

As a starting point see: https://github.com/devitocodes/tutorial-hands-on/blob/master/01_introduction.ipynb.

**Comment by EdCaunt** [comment]
I'm guessing this will want to be in a directory inside devito/examples?

**Comment by rhodrin** [comment]
> I'm guessing this will want to be in a directory inside devito/examples?

Yes, under `userapi`.

**Comment by FabioLuporini** [comment]
yes, I agree

**Comment by ggorman** [comment]
https://github.com/navjotk/devitoworkshop/blob/master/01-sympy.ipynb

**Comment by FabioLuporini** [comment]
closing, see  #1108 

discussing on Slack about the addition of https://github.com/navjotk/devitoworkshop/blob/master/01-sympy.ipynb
