### ISSUE TITLE
Deploy Jupyterhub on Azure for Devito tutorial

### ISSUE THREAD

**Issue by ggorman** [devitocodes/devito#1100]
requirements:
- devito install
- mpi support
- jupyterhub

**Comment by ggorman** [comment]
https://techcommunity.microsoft.com/t5/educator-developer-blog/deploying-jupyterhub-on-azure-for-individual-students-or-class/ba-p/1120309

**Comment by georgebisbas** [comment]
Is there any other reason than a small overhead in cost to setup different lab for #1100 rather than use the one created for #1101? By the way is there any rough estimation of how many participants are expected?

**Comment by ggorman** [comment]
May use the same solution as #1101

**Comment by ggorman** [comment]
We established that Azure Lab Services cannot be used here because we cannot (without resorting to ssh tunnelling etc) connect to JupyterHub running on nodes because there is no public IP.

Apparently there is something in the pipeline but not in time for Rice.

**Comment by georgebisbas** [comment]
I guess that as long as we will not need GPUs here, we could have a FAT VM for everybody to connect through Jupyterhub.

**Comment by georgebisbas** [comment]
So this is in good shape. Few details remaining. 
http://52.191.134.114

**Comment by georgebisbas** [comment]
Connect to: http://13.66.135.195
New -> Terminal
git clone https://github.com/devitocodes/devito.git
cd devito
pip install --user -e .[extras]
Navigate through devito and run tutorials.

**Comment by georgebisbas** [comment]
@ggorman I think after I just ensured that MPI works here we are ready for the dry run.
