### ISSUE TITLE
Setup Azure labs for Devito GPU hackathon

### ISSUE THREAD

**Issue by ggorman** [devitocodes/devito#1101]
https://azure.microsoft.com/en-gb/services/lab-services/

Requirements:
- Devito install
- mpi support
- GPU VM's
- OpenMP 5
- JupyterHub/JupyterLab
- ssh (may not be needed as one could also use the terminal in JupyterLab)

**Comment by ggorman** [comment]
See https://techcommunity.microsoft.com/t5/educator-developer-blog/deploying-jupyterhub-on-azure-for-individual-students-or-class/ba-p/1120309

**Comment by ggorman** [comment]
An alternative approach is to use https://cloudlabs.ai/ 
Cloudlabs.ai uses a central pool of Azure subscriptions where there is a support team that can take care of lab issues, and also making sure we have the GPU capacity. Additionally, the cost is charged to a central team, and it would give more freedom for participants to choose different VMs etc.

However, a potential issue with CloudLabs is that it essentially requires users to have covered Azure Fundamentals. It would be easy to spend the first couple of hours teaching people how to use the portal.

I suggest we get a working demo first with Azure labs and then revisit CloudLabs.

**Comment by georgebisbas** [comment]
Currently Azure Labs are able to support the hackathon for the afternoon session. I would like to do the stress test. JupyterHub/JupyterLab support is not included without SSH tunelling as the VMs do not have a public IP.
