### ISSUE TITLE
Add ARM testing CI through github actions

### ISSUE THREAD

**Issue by georgebisbas** [devitocodes/devito#1106]

**Comment by ggorman** [comment]
https://github.blog/changelog/2019-12-03-github-actions-self-hosted-runners-on-arm-architectures/

**Comment by FabioLuporini** [comment]
@ggorman do we still want this?

**Comment by georgebisbas** [comment]
If you do not mind, I would be interested to go through this in the future. However there is no need to keep the issue if you do not want to.

**Comment by FabioLuporini** [comment]
yes we can keep it, I was more curious about what opinion does Gerard have on ARM

**Comment by FabioLuporini** [comment]
@georgebisbas I don't think ARM is a platform of primary interest at this stage, but I agree we could have at least a tiny action that only attempts to install devito and run a bunch of tests. How long do you think this might take to set up?

**Comment by mloubout** [comment]
From what I've seen, we would only be able to do generated code tests, I don't think there is any ARM VMs on Azure. I know some people are interested but acees to it still very limited IMO so low priority
