### ISSUE TITLE
GPU notebook tutorial

### ISSUE THREAD

**Issue by rhodrin** [devitocodes/devito#1112]
Notebook with GPU offloading. ~Needed for OGHPC~.

Edit: After further discussions this is no longer needed for OGHPC, but we may want one at some point regardless? Please feel free to close this issue for now if we don't want to think about this for the time being.

**Comment by ggorman** [comment]
It might not be needed for the OGHPC morning tutorial BUT it would be very useful for the afternoon tutorial and we have several people asking how to use it already.

**Comment by FabioLuporini** [comment]
I actually think it's a must for Rice?
