### ISSUE TITLE
JIT compilation SIMD warning

### ISSUE THREAD

**Issue by georgebisbas** [devitocodes/devito#1120]
When DEVITO_ARCH is not explicitly set and Devito uses `CustomCompiler`, SIMD directives are being ignored.

@FabioLuporini -fopenmp  should be added regardless of DEVITO_OPENMP, for SIMD vectorization. With gcc we automatically add it if we find out the compiler version is >=4.9 (which are then guaranteed to implement openmp3).

**Comment by FabioLuporini** [comment]
yes I think we should add a special patch that checks whether the detected compiler is gcc>=4.9 and, at least in that case (the very most common case!), add the -fopenmp. 

Do you think you can write a quick patch? just check self.cc and self.version and if all good, add -fopenmp. Do you have a compiler to test it?

**Comment by FabioLuporini** [comment]
I have a better idea.

How about we add `__new__` to `CustomCompiler` and if we see it's `gcc` or `clang`, we return the class object of appropriate type? @mloubout

**Comment by FabioLuporini** [comment]
closing as fixed by #1263
