### ISSUE TITLE
Problems with Installation

### ISSUE THREAD

**Issue by TatianaApril** [devitocodes/devito#1122]
Hello! 
I'm trying to install devito on Win10. Neither conda env nor pip install works for me. It's in a great need of gcc and no gcc-for-win helps :(
So I tried to install it with docker toolbox. There is an error:
`C:\Users\asus\devito>docker-compose up devito`
`Starting devito_devito_1 ... done `                                                           
`Attaching to devito_devito_1`
`devito_1  | /usr/bin/env: ‘bash\r’: No such file or directory`
`devito_devito_1 exited with code 127`
I know that problem is in `n\r\` endings in [name].sh files, but I can't fix it. Help me please

**Comment by navjotk** [comment]
Can you follow the instructions [here](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings) to enable git's automatic line-ending handling? I think the following command should do it:
```
git config --global core.autocrlf input
```

This should fix the line endings in your clone of Devito. The docker command should work fine after that.

**Comment by TatianaApril** [comment]
> Can you follow the instructions [here](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings) to enable git's automatic line-ending handling? I think the following command should do it:
> 
> ```
> git config --global core.autocrlf input
> ```
> 
> This should fix the line endings in your clone of Devito. The docker command should work fine after that.

I've already tried it, but unfortunately it didn't help. Maybe there is the way to rewrite this endings by hands in NotePad++?

**Comment by TatianaApril** [comment]
Well, I've tride to change endings using NotePad++, but also failed.
1) Menu: Search in Files
2) Finde \r\n
3) Remove with \n
4) Extand Search

Some files in `.git` are only for reading, may be it is a root of problem

**Comment by TatianaApril** [comment]
Solved!
What I did:
1) Open GIT CMD as Admin, paste `git config --global core.autocrlf input`
2) Open NotePad++ and changed all the `\r\n & \r endings to \n`
In a couple this two work just fine.

Now I have just another problem.
After `docker-compose up devito` command:

```
Starting devito_devito_1 ... done                                                                                       
Attaching to devito_devito_1
devito_1  | [I 18:53:25.599 NotebookApp] Loading IPython parallel extension
devito_1  | [I 18:53:25.601 NotebookApp] Serving notebooks from local directory: /app
devito_1  | [I 18:53:25.601 NotebookApp] The Jupyter Notebook is running at:
devito_1  | [I 18:53:25.601 NotebookApp] http://65f5dec93beb:8888/?token=b9618ef4dd4973c96e03d1cd2429182269bed67159fe72ec
devito_1  | [I 18:53:25.602 NotebookApp]  or http://127.0.0.1:8888/?token=b9618ef4dd4973c96e03d1cd2429182269bed67159fe72ec
devito_1  | [I 18:53:25.602 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
devito_1  | [W 18:53:25.611 NotebookApp] No web browser found: could not locate runnable browser.
```
Neither URL nor Token works.
I generate jupyter_notebook_config and changed some lines:
```
#import browser
#c.NotebookApp.browser = "C:/Program Files/Mozilla Firefox/firefox.exe %s"
```
```
#c.NotebookApp.ip = '0.0.0.0'
```
```
#c.NotebookApp.allow_origin = '*'
```
I tried with Chrome and Firefox both, but nothing works.

**Comment by TatianaApril** [comment]
And finaly solved!!!! 
What to do, if you have this problem:
In CMD, starting env: 
```
docker-machine start default
docker-machine env
FOR /f "tokens=*" %i IN ('docker-machine env --shell cmd default') DO %i
set dock
```
Then you need to know your IP: `docker-machine ip`
After `docker-compose up devito` you'll get an URL: 
`http://127.0.0.1:8888/?token=TOKEN`
Just copy your machine IP and paste it instead of "127.0.0.1", it will look like:
```
http://IP:8888/?token=TOKEN
```
So it will work in any browser!

**Comment by georgebisbas** [comment]
Hi Tatiana, glad that you managed to solve this issue. Let us know if anything new emerges.
Thanks.
