### ISSUE TITLE
Automatically get rid of norms*.npy

### ISSUE THREAD

**Issue by georgebisbas** [devitocodes/devito#1133]
Any way to speed up local testing by avoiding deleting the norms ?
Keeping the norms fails test_mpi.py.

**Comment by FabioLuporini** [comment]
this is indeed a bug in our testing infrastructure

**Comment by mloubout** [comment]
Ok I'm confused by the first message, you want to keep the norms and not keep the norms at the same time?

**Comment by georgebisbas** [comment]
Ideally norms should be deleted when they are not needed anymore. If norms are kept, the mpi tests fail.
