### ISSUE TITLE
Redundant subdimensions being created when finalizing subdomains

### ISSUE THREAD

**Issue by rhodrin** [devitocodes/devito#1135]
When attaching  M `SubDomain`'s to an N-dimensional grid M*N `SubDimension`'s are currently being created, but often some `SubDimension`'s can, and should, be re-used.

Therefore, during the finalization of a `SubDomain` a check should be carried out to see if a previously created `SubDimension` can be used. An easy way to this would be to at, e.g., a `grid._subdimensions` property which is checked against and appended too during the finalization of each `SubDomain`.

**Comment by mloubout** [comment]
@EdCaunt is this now fixed with all the new updates?

**Comment by EdCaunt** [comment]
Yes. SubDimensions are now unique for concretisation, but their names in the generated code are abridged by the `abridge_dim_names` compiler pass.
