### ISSUE TITLE
Dockerfile to do the heavy lifting for users that want to do local GPU runs. [OpenMP offloading only]

### ISSUE THREAD

**Issue by georgebisbas** [devitocodes/devito#1150]
Dockerfile to do the heavy lifting for users that want to run on GPUs

**Comment by georgebisbas** [comment]
Ideally this should be GPU compute capability agnostic, correct?
Remind me of something please. Did we manage to get the V100 working after Houston?

**Comment by FabioLuporini** [comment]
@georgebisbas maybe that's what @jaimesouza produced?

**Comment by jaimesouza** [comment]
@georgebisbas, I have a llvm/clang 11 (with offloading and SMs 35,37,50,52,60,61,70,75) image available on dockerhub. I can add devito to that image and push it again if It's useful.

**Comment by georgebisbas** [comment]
That would be lovely Jaime, is the image public?

**Comment by jaimesouza** [comment]
Yes, It is. So, I am gonna add devito and create a new image. And will send the link to you in a couple of hours.

**Comment by jaimesouza** [comment]
This is the image:

https://hub.docker.com/r/hpcufscar/llvm11-devito-gpu

docker pull hpcufscar/llvm11-devito-gpu:v4.2.1

**Comment by georgebisbas** [comment]
Thanks for posting that @jaimesouza I will have a look at this image during this week.

**Comment by FabioLuporini** [comment]
@rhodrin @georgebisbas what do we wanna do with this?

**Comment by georgebisbas** [comment]
Sorry I totally forgot. I need some more time. I will check it at some point in the next days.
.

**Comment by mloubout** [comment]
This was fixed in #1392 no?

**Comment by FabioLuporini** [comment]
yes. @jaimesouza , what's the delta between your work and what we have in master today?

**Comment by jaimesouza** [comment]
I haven't seen the master dockerfile. My work has only llvm/clang 10 environment (OpenMP offloading) for Nvidia GPUs and it's an image.

**Comment by FabioLuporini** [comment]
We probably want something analogous for openmp offloading

**Comment by georgebisbas** [comment]
@FabioLuporini @italoaug
