### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by mariosgeo** [devitocodes/devito#1151]
Hi, I installed Devito using the git repository. 
I am using the windows 10 subsystem for linux and anaconda installation. 
Installation finishes without any warnings, but when I 

    from examples.seismic import Model, plot_velocity
    # Define a physical size
    shape = (101, 101)  # Number of grid point (nx, nz)
    spacing = (10., 10.)  # Grid spacing in m. The domain size is now 1km by 1km
    origin = (0., 0.)  # What is the location of the top left corner. This is necessary to define
    # the absolute location of the source and receivers

    # Define a velocity profile. The velocity is in km/s
    v = np.empty(shape, dtype=np.float32)
    v[:, :51] = 1.5
    v[:, 51:] = 2.5

    # With the velocity and model size defined, we can create the seismic model that
    # encapsulates this properties. We also define the size of the absorbing layer as 10 grid points
    model = Model(vp=v, origin=origin, shape=shape, spacing=spacing,
              space_order=2, nbl=10)

Then it reports back 

/home/marios/anaconda3/envs/python37/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/marios/anaconda3/envs/python37/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib/../lib/Scrt1.o: in function `_start':
/home/conda/feedstock_root/build_artifacts/ctng-compilers_1580517382604/work/.build/src/glibc-2.12.2/csu/../sysdeps/x86_64/elf/start.S:99: undefined reference to `main'
collect2: error: ld returned 1 exit status
FAILED compiler invocation:/home/marios/anaconda3/envs/python37/bin/x86_64-conda_cos6-linux-gnu-cc -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/marios/anaconda3/envs/python37/include -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/marios/anaconda3/envs/python37/lib -Wl,-rpath-link,/home/marios/anaconda3/envs/python37/lib -L/home/marios/anaconda3/envs/python37/lib /tmp/devito-jitcache-uid1000/8bb9dff89c3f2b6d1d6b244235cce2acc61cb650.c -lm -o /tmp/devito-jitcache-uid1000/8bb9dff89c3f2b6d1d6b244235cce2acc61cb650.so

I supposed it can't find the compiler? Could you please advise how to fix this?

**Comment by FabioLuporini** [comment]
can you provide the output of

```
echo $CC
echo $CXX
echo $CFLAGS
echo $LDFLAGS
echo $OMP_LDFLAGS
```

what compilers do you have at your disposal? what do the following commands return:
```
gcc --version
```
and
```
clang --version
```

**Comment by mariosgeo** [comment]
(python37) marios@L01834:~$ echo $CC
/home/marios/anaconda3/envs/python37/bin/x86_64-conda_cos6-linux-gnu-cc

(python37) marios@L01834:~$ echo $CXX
/home/marios/anaconda3/envs/python37/bin/x86_64-conda_cos6-linux-gnu-c++

(python37) marios@L01834:~$ echo $CFLAGS
-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/marios/anaconda3/envs/python37/include

(python37) marios@L01834:~$ echo $LDFLAGS
-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/marios/anaconda3/envs/python37/lib -Wl,-rpath-link,/home/marios/anaconda3/envs/python37/lib -L/home/marios/anaconda3/envs/python37/lib
(python37) marios@L01834:~$ echo $OMP_LDFLAGS

(python37) marios@L01834:~$ gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(python37) marios@L01834:~$ clang --version

Command 'clang' not found, but can be installed with:

sudo apt install clang

**Comment by FabioLuporini** [comment]
can you try running with the environment variable: ``DEVITO_ARCH=gcc`` set ?

what's happening is that Devito is assembling a custom compiler based on CC/CFLAGS/... but somewhat they have preset odd values on your system...

**Comment by mariosgeo** [comment]
Alright! 
I set to the .bashrc the export DEVITO_ARCH=gcc and did the trick.
Great, thanks a lot.
