### ISSUE TITLE
Potentially wrong `shape_with_halo` with HALO > DOMAIN

### ISSUE THREAD

**Issue by FabioLuporini** [devitocodes/devito#1166]
This might cause NaNs or segfaults by essentially breaking the contract between python-land and generated code

Reproducer here: https://github.com/devitocodes/devito/compare/fix-shape-with-halo

For an Operator that produces NaNs, take [this test](https://github.com/devitocodes/devito/blob/consolidate-aliases-3/tests/test_dse.py#L582
) and change the grid such that, in at least one decomposed Dimension, it's smaller than the halo size, for example (3, 3, 3)
it will produce garbage values -- but you have to run it many times until it produces NaNs, thus causing np.close to fail ! or make the test "more reasonable" such that it produces a given expected value against which you can assert deterministically

**Comment by FabioLuporini** [comment]
@rhodrin I haven't forgotten about this -- I know the two of us need to talk about this issue. Let's try (finally) tomorrow

**Comment by rhodrin** [comment]
@FabioLuporini Sounds good. To recap, the decomposition bug if fixed in `https://github.com/devitocodes/devito/compare/fix-shape-with-halo2`, but then we need to decide how we want to feedback this bug fix into the outhalo shape calculation (since this fix alone wont solve the underlying problem).
