### ISSUE TITLE
Devito CFD tutorials

### ISSUE THREAD

**Issue by jkwashbourne** [devitocodes/devito#1185]
### 01_convection.ipynb
 - [ ] Suggest noting that u[:,-1] notation is shorthand for the maximum
 - [ ] In cell [4] last sentence, it was not clear to me that the 3d array u[t,x,y] could be indexed as u[0] to provide u[0,x,y]. Is this a numpy shorthand?
 - [ ] Cell [6]: wondering why the "1.0*" doesn't disappear?
 - [ ] Cell [6]: you refer to "s" and "h" but they are not seen here. Did the output from print(eq) change? We do see "h_x" and "h_y" in cell [7].
 - [ ] Cell [7]: discussion uses "h" but stencil uses "h_x" and "h_y". Note there is continuing confusion about "s", "dt".
 - [ ] I needed "%matplotlib inline" here also, must be my setup is whack
 - [ ] Cell [9]: I was expecting a smaller tolerance after implementing the BCs, what gives? Should the Devito result with no optimization be float eps equivalent to the numpy one? 

### 01_convection_revisited.ipynb
 - [ ] s/exampe/example/
 - [ ] Cell [9] uses "nx - 1" instead of "-1" notation, consistency?
 - [ ] Again schizo on "-1" and "n-1" notation for end of array

### 02_convection_nonlinear.ipynb
 - [ ] Cell [1] here has "%matplotlib inline", suggest adding to the others in the first cell
 - [ ] "s/hte/the/"
 - [ ] "s/woth/with/"
 - [ ] Cell [8]: A couple more words on the "automated staggering of vectorial function" would be super useful

### 03_diffusion.ipynb
 - [ ] Cell [3]: omg such a python n00b, I had to go look up the "//" operator. Is it worth noting what that operator does? Maybe not since you have the plot just below.
 - [ ] Cell [4] is a partial duplicate of cell [3]?
 - [ ] Cell [7], [8] there is inconsistency in line feeds ... [not sure anyone should care about this level of pedantry]
 - [ ] Cell [7] and [8] seem redundant

### 03_diffusion_nonuniform.ipynb
 - [ ] Suggest clarification: "This example is an enhancement of 03_diffusion in terms of having non-uniform viscosity as opposed to 03_diffusion" --> "This example is an enhancement of 03_diffusion in terms of having non-uniform viscosity"
 - [ ] Suggest clarification: "In our case ν(x,y) is depended on the material properties as we may have different viscosity for a (x,y) pair. So ν(x,y) is not uniform." --> "In our case v is not uniform and ν(x,y) represents spatially variable viscosity."
 - [ ] Cell [4] and [5]: suggest not re-using all the same language from 03_diffusion.ipynb about the "trick" of the laplace operator, as you already did that.
 - [ ] Cell [7] and [8] seem redundant
 
### 04_burgers.ipynb
 - [ ] Cell [1]: "# Increase number of batches to extend evolution in time" is used way too many times

### 05_laplace.ipynb
 - [ ] The most confusing thing about this tuto is the BCs. I think a little more time thinking about how to make it more easy to understand would be super useful. 
 - [ ] Cell [3]: "s/Out initial condition/Our initial condition/"
 - [ ] Cell [3]: are the labels wrong on the plot due to the (y,x) weirdness? The BC "# p = y @ x = 2" looks more like "# p = x/2 @ y = 1"
 - [ ] Same confusion in cell [7]
 - [ ] Cell [6]: "s/where we wet/where we want"
 - [ ] I think cells [6] and [7] need more words
 - [ ] I note that the first figure from cell [3] and the first figure from cell [8] look different. This appears to be some kind of rat dropping at x=0, y=1

### 06_poisson.ipynb
 - [ ] <nitpick> above cell [1]: "−100  at i=nx∗3/4,j=3/4ny" --> "−100  at i=3/4 nx,j=3/4 ny"
 - [ ] Cell [3]: the comment "# Now with Devito we will turn `p` into `TimeFunction` object to make all the buffer switching implicit" seems to jumping the gun, and belongs in a cell below
 - [ ] Cell [3]: More schizophrenia with notation [nx-1,:] or [-1,:]
 - [ ] Suggest adding a comparison of the final pure python code and the devito code for a large enough model to demonstrate a big performance delta

### overall
  - [ ] maybe renumber these sequentially?

**Comment by FabioLuporini** [comment]
fixed by #1360
