### ISSUE TITLE
Update FAQ page

### ISSUE THREAD

**Issue by FabioLuporini** [devitocodes/devito#1195]
First of all, add links to it from README and website

Secondly, here's some new questions/answers from @jkwashbourne 

*.Where does generated code go and how do I look at it
TMP variable?
* What environment variables control how devito works
Aggressiveness of optimization?
TMP dir for generated code
Backdoor
MPI
OPENMP
GPU
LOG LEVEL
* How do you run the tests from the command line
Py.test <test.py>
Py.test -vs <test.py>  [more detailed log]
* What is the difference between op() and op[] notation
Bla bla ... indexify ... bla (link to indexify tuto?)
Is there a flow chart?
* Simple flow chart for equation --> code, with links from each step to the API docs
What's up with <object>.data
Bla bla numpy array backend
* What are the keys to fast code 
CPU: Cache blocking, loop fusing, alignment to promote SIMD, ...
GPU: longer pipelines, less travel to host
* As time increases in the finite difference evolution, are wavefield arrays "swapped" like you might see in c/c++ code?
No, devito uses the modulus of a time index to map increasing indices [0, 1, 2, 3, 4, 5, ...] into cyclic indices [0, 1, 2, 0, 1, 2, ...]
* What are units typically used in devito examples
Sampling rates: msec
Frequency: KHz
Velocity: km/sec

**Comment by georgebisbas** [comment]
Related to #841

**Comment by georgebisbas** [comment]
Updated some env variables here:
https://github.com/devitocodes/devito/wiki/FAQ#how-to-set-devito-environment-variables mostly copying from code documantation.
As far as I can see, only left is 
DEVITO_FIRST_TOUCH and DEVITO_IGNORE_UNKNOWN_PARAMS.

Then we should be able to close both #841 and #1195.

**Comment by FabioLuporini** [comment]
Closing as now the wiki page is updated with all env vars
