### ISSUE TITLE
documentation updates

### ISSUE THREAD

**Issue by jkwashbourne** [devitocodes/devito#1199]
- [ ] http://devitocodes.github.io/devito/
    - [ ] tutorials
        - [ ] compiler (http://devitocodes.github.io/devito/compiler.html)
        - [ ] user api (https://github.com/devitocodes/devito/tree/master/examples/userapi) 
    - [x] add FAQ link (https://github.com/devitocodes/devito/wiki/FAQ) to left side list [Download, Tutorials, API Reference, The Devito Compiler)

**Comment by FabioLuporini** [comment]
closing as addressed by #1299
