### ISSUE TITLE
Fix Devito publications list

### ISSUE THREAD

**Issue by jkwashbourne** [devitocodes/devito#1208]
the Devito publications at https://www.devitoproject.org/publications needs work
- [ ] make references uniform (pick a style and use everywhere)
- [ ] dates are missing from many references 
    - [ ] a possibility might be to add headings for years
- [ ] add related phd thesis (e.g. @FabioLuporini)
- [ ] consider adding contact information for authors associated with Devito (possibly exists already somewhere else)

**Comment by FabioLuporini** [comment]
I guess nobody is ever gonna fix this

**Comment by mloubout** [comment]
Would be good to just not at the top of TODO list. I guess next publication added does it.

**Comment by mloubout** [comment]
I think @ggorman fixed this no?

**Comment by georgebisbas** [comment]
Mostly yes, but e.g. style is still not uniform

**Comment by FabioLuporini** [comment]
We've made a lot of updates to that page over time. Unfortunately, it's a Cauchy sequence, but overall, I'm satisfied with its current state. Hence, I declare this fixed
