### ISSUE TITLE
Non-padding of the halo could cause incorrect computed values

### ISSUE THREAD

**Issue by speglich** [devitocodes/devito#1250]
The following example results in NaN values.

```python

    grid = Grid(shape=(5,5))
 
    v = VectorTimeFunction(name="v", grid=grid, time_order=1, space_order=4)
    p = TimeFunction(name="p2", grid=grid, time_order=1, space_order=4, staggered=NODE)

    v[0].data[:] = 5.
    v[1].data[:] = 5.
 
    den = np.zeros((5,5), dtype=np.float32)
    den[:] = 2.

    B = Function(name="B", grid=grid, space_order=4, staggered=NODE)
    initialize_function(B, den, 0, dtype=np.float32)
    b = 1./B

    eq = Eq(p, div(b*v))
    op = Operator([eq])
    op.apply(time_M=0)
```

 
This NaN values are coming from non-padding of the halo in B. More precisely this occurs because the halo, non padded, is used in the derivative on B leading to 1/0.

As suggest by @mloubout padding the B as ` B._data_with_outhalo[:] = 2 ` solve this problem manually for this case.

**Comment by FabioLuporini** [comment]
a different symptom of the same issue is given in #1432
