### ISSUE TITLE
MPIRegion pickle_args inconsistent with constructor

### ISSUE THREAD

**Issue by tjb900** [devitocodes/devito#1286]
Hi!

We're hitting this error, since MPIRegion needs to be pickled when pickling an Operator - as needed to avoid building operators on every node of a job.

```
TypeError: __init__() missing 1 required positional argument: 'owned'
```

It appears to be caused by this:

```
class MPIRegion(CompositeObject):

    def __init__(self, name, key, arguments, owned):
        name = "%s%d" % (name, key)
        pname = "region%d" % key
...

    # Pickling support
    _pickle_args = ['name', 'arguments', 'owned']
```

I don't have an MFE to hand yet, sorry.

**Comment by FabioLuporini** [comment]
there are multiple pickling issues with the MPI full mode. Looking into this

**Comment by FabioLuporini** [comment]
I'm fixing this and other minor pickling bugs in #1291 

lemme know when you can! Thanks for reporting
