### ISSUE TITLE
Tutorials failing

### ISSUE THREAD

**Issue by rsarkar-github** [devitocodes/devito#1336]
The tutorial 01_modelling.ipynb is not working. This was working when I installed devito 2 weeks back, but after reinstalling it yesterday, this has stopped working. The error originates on this line

**model = Model(vp=v, origin=origin, shape=shape, spacing=spacing,
              space_order=2, nbl=10)**

The error message is pasted below.
**************************************************************************************************
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-43ef486b0231> in <module>
     15 # With the velocity and model size defined, we can create the seismic model that
     16 # encapsulates this properties. We also define the size of the absorbing layer as 10 grid points
---> 17 model = Model(vp=v, origin=origin, shape=shape, spacing=spacing,
     18               space_order=2, nbl=10)
     19 

/net/server2/homes/sep/rahul/devito-new/examples/seismic/model.py in __init__(self, origin, spacing, shape, space_order, vp, nbl, dtype, epsilon, delta, theta, phi, subdomains, damp_mask, **kwargs)
    208 
    209         # Create square slowness of the wave as symbol `m`
--> 210         self._vp = self._gen_phys_param(vp, 'vp', space_order)
    211 
    212         # Additional parameter fields for TTI operators

/net/server2/homes/sep/rahul/devito-new/examples/seismic/model.py in _gen_phys_param(self, field, name, space_order, is_param, default_value)
    111             function = Function(name=name, grid=self.grid, space_order=space_order,
    112                                 parameter=is_param)
--> 113             initialize_function(function, field, self.nbl)
    114         else:
    115             function = Constant(name=name, value=field)

/net/server2/homes/sep/rahul/devito-new/devito/builtins.py in initialize_function(function, data, nbl, mapper, mode, name, **kwargs)
    353         options = None
    354 
--> 355     assign(lhs, rhs, options=options, name=name, **kwargs)
    356 
    357 

/net/server2/homes/sep/rahul/devito-new/devito/builtins.py in assign(f, rhs, options, name, **kwargs)
     67         for i, j in zip(as_list(f), rhs):
     68             eqs.append(dv.Eq(i, j))
---> 69     dv.Operator(eqs, name=name, **kwargs)()
     70 
     71 

/net/server2/homes/sep/rahul/devito-new/devito/backends.py in __call__(cls, *args, **kwargs)
     71             raise e
     72         # Invoke the constructor with the arguments given
---> 73         return t(*args, **kwargs)
     74 
     75     # More disgusting metaclass voodoo

/net/server2/homes/sep/rahul/devito-new/devito/operator/operator.py in __new__(cls, expressions, **kwargs)
    154         # Lower to a JIT-compilable object
    155         with timed_region('op-compile') as r:
--> 156             op = cls._build(expressions, **kwargs)
    157         op._profiler.py_timers.update(r.timings)
    158 

/net/server2/homes/sep/rahul/devito-new/devito/operator/operator.py in _build(cls, expressions, **kwargs)
    181 
    182         # Group expressions based on iteration spaces and data dependences
--> 183         clusters = cls._lower_clusters(expressions, profiler, **kwargs)
    184 
    185         # Lower Clusters to a ScheduleTree

/net/server2/homes/sep/rahul/devito-new/devito/tools/decorators.py in __call__(self, *args, **kwargs)
    161 
    162         tic = time()
--> 163         retval = self.func(*args, **kwargs)
    164         toc = time()
    165 

/net/server2/homes/sep/rahul/devito-new/devito/operator/operator.py in _lower_clusters(cls, expressions, profiler, **kwargs)
    356         """
    357         # Build a sequence of Clusters from a sequence of Eqs
--> 358         clusters = clusterize(expressions)
    359 
    360         # Operation count before specialization

/net/server2/homes/sep/rahul/devito-new/devito/ir/clusters/algorithms.py in clusterize(exprs)
     21 
     22     # Setup the IterationSpaces based on data dependence analysis
---> 23     clusters = Schedule().process(clusters)
     24 
     25     # Handle ConditionalDimensions

/net/server2/homes/sep/rahul/devito-new/devito/tools/decorators.py in __call__(self, *args, **kwargs)
    161 
    162         tic = time()
--> 163         retval = self.func(*args, **kwargs)
    164         toc = time()
    165 

/net/server2/homes/sep/rahul/devito-new/devito/ir/clusters/algorithms.py in process(self, clusters)
     77     @timed_pass(name='schedule')
     78     def process(self, clusters):
---> 79         return self._process_fdta(clusters, 1)
     80 
     81     def callback(self, clusters, prefix, backlog=None, known_break=None):

/net/server2/homes/sep/rahul/devito-new/devito/ir/clusters/queue.py in _process_fdta(self, clusters, level, prefix)
     51             else:
     52                 # Recursion
---> 53                 processed.extend(self._process_fdta(list(g), level + 1, pfx))
     54 
     55         # Apply callback

/net/server2/homes/sep/rahul/devito-new/devito/ir/clusters/queue.py in _process_fdta(self, clusters, level, prefix)
     51             else:
     52                 # Recursion
---> 53                 processed.extend(self._process_fdta(list(g), level + 1, pfx))
     54 
     55         # Apply callback

/net/server2/homes/sep/rahul/devito-new/devito/ir/clusters/queue.py in _process_fdta(self, clusters, level, prefix)
     54 
     55         # Apply callback
---> 56         processed = self.callback(processed, prefix)
     57 
     58         return processed

/net/server2/homes/sep/rahul/devito-new/devito/ir/clusters/algorithms.py in callback(self, clusters, prefix, backlog, known_break)
     90         candidates = prefix[-1].dim._defines
     91 
---> 92         scope = self._fetch_scope(clusters)
     93 
     94         # Handle the nastiest case -- ambiguity due to the presence of both a

/net/server2/homes/sep/rahul/devito-new/devito/ir/clusters/queue.py in _fetch_scope(self, clusters)
     99         key = tuple(exprs)
    100         if key not in self.state.scopes:
--> 101             self.state.scopes[key] = Scope(exprs)
    102         return self.state.scopes[key]
    103 

/net/server2/homes/sep/rahul/devito-new/devito/ir/support/basic.py in __init__(self, exprs, rules)
    703 
    704             # If writing to a scalar, we have an initialization
--> 705             if not e.is_Increment and e.is_scalar:
    706                 self.initialized.add(e.lhs.function)
    707 

AttributeError: 'ClusterizedEq' object has no attribute 'is_scalar'

**Comment by georgebisbas** [comment]
HI @rsarkar-github , there was a recent update in sympy that triggered this error as said around 2-3 weeks ago. Did you update your sympy? As per devito reqiurements.txt your sympy should be sympy<1.6. Can you confirm?

**Comment by rsarkar-github** [comment]
Ok, the error went away with sympy < 1.6
