### ISSUE TITLE
Question: How to fix values at specific internal grid points

### ISSUE THREAD

**Issue by swfc** [devitocodes/devito#1340]
Hi,
How do I fix values at internal grid points so that they are removed from the solve?

Thankyou!

**Comment by mloubout** [comment]
You can use the indexed notation to set the value of any point. You can look for example at  the CFD notebooks were we use it to fix the value at the boundary. So something like
`Eq(u[t, myx, myy], myvalue)`

**Comment by FabioLuporini** [comment]
@swfc I'm assuming @mloubout explained it. I'm gonna close this, but feel free to reopen if you need for clarifications.
