### ISSUE TITLE
Temporal additive white noise

### ISSUE THREAD

**Issue by smcantab** [devitocodes/devito#1384]
Is there a simple way of adding white noise to the field between iterations of, say, forward Euler? I am looking to solve a stochastic differential equation with additive noise in devito (it boils down to sampling from a normal distribution and perturb the field after every iteration of forward Euler). If so, I would be happy to contribute the example.

**Comment by mloubout** [comment]
You can use the standard rand for it threw sympy function, i.e.:

```
Eq(u.forward, stencil + sympy.Function('rand()`)
```

@FabioLuporini not sure I remember the syntax exactly.

**Comment by FabioLuporini** [comment]
yeah you can use any function from the C stdlib through sympy, I think it's something along the lines of

```
sympy.Function('rand')()
```

and then you can use it in any expression

we've been talking for a while about a neater API to call custom functions from within an Operator, but we're not quite there yet. @mloubout is right, `sympy.Function` gives you an alternative for now, and that's what you probably wanna use

**Comment by smcantab** [comment]
Great, we'll contribute the example when we're done implementing it!

**Comment by smcantab** [comment]
I am reopening this because it just occurred to me that 'rand' samples from a uniform distribution, and for white noise one must sample from a normal distribution. As of recently Sympy supports sampling from arbitrary distributions (full PR [here](https://github.com/sympy/sympy/pull/19342)) from other python libraries (numpy, scipy, pymc3). For instance
```python
from sympy.stats import *
N = Normal('N',0,1)
sample(N, library='numpy')
```
will return a random sample from a normal distribution. Would devito be able to take something like this? Maybe we could defined a class from `Function` that wraps this function into a method that devito can deal with? There is a similar new functionality in sympy, named `sample_stochastic_process` (PR [here](https://github.com/sympy/sympy/commit/4a958b9a017b619c9fea58d3aa49ceac99977463))

**Comment by FabioLuporini** [comment]
let's put it this way -- what kind of C code would you like to see generated?

**Comment by smcantab** [comment]
It'd have to be the c code to generate a random normal, e.g. by Box-Muller transform
```c
double r1 = ((double) rand() / (RAND_MAX));
double r2 = ((double) rand() / (RAND_MAX));
double rnormal = cos(2*M_PI*r2)*sqrt(-2.*log(r1));
```

**Comment by smcantab** [comment]
You could write it as a one liner (with <math.h> and <stdlib.h> dependencies)
```c
cos(2*M_PI*((double) rand() / (RAND_MAX)))*sqrt(-2.*log(((double) rand() / (RAND_MAX))));
```

**Comment by FabioLuporini** [comment]
@smcantab both `math.h` and `stdlib.h` should be included by default, so that's fine.

can you write that one-liner in pure sympy? devito should just be able to swallow it.

Alternatively, you may either have a class in user code (if that's more convenient for you), or we may actually welcome a contribution to devito directly. We have a few sympy extensions [here](https://github.com/devitocodes/devito/blob/master/devito/symbolics/extended_sympy.py) and for custom code printing you may add a handler [here](https://github.com/devitocodes/devito/blob/master/devito/symbolics/printer.py#L121)

Let us know how you decide to move on, we're glad to give feedback. Thanks!

**Comment by FabioLuporini** [comment]
@smcantab let me know if/when I can close the issue

**Comment by smcantab** [comment]
Closing it for now, will reopen if I run into trouble implementing the suggestions
