### ISSUE TITLE
tutorial seismic FWI failing

### ISSUE THREAD

**Issue by AlbertZhangHIT** [devitocodes/devito#1401]
Failure in tutorial FWI:
```
Traceback (most recent call last):
  File "fwi_test_new.py", line 29, in <module>
    assert model.grid == model0.grid
AssertionError
```
where the `model.grid` and `model0.grid` are printed as
```
Grid[extent=(1800.0, 1800.0), shape=(181, 181), dimensions=(x, y)]
Grid[extent=(1800.0, 1800.0), shape=(181, 181), dimensions=(x, y)]

```
If I comment out the assersion line, FWI fails to converge
```
Objective value is 57280.450273 at iteration 1
Objective value is 298451.910653 at iteration 2
Objective value is 358773.604241 at iteration 3
Objective value is 220326.398016 at iteration 4
Objective value is 331333.849494 at iteration 5

```
Evironment: Ubuntu 18.0
devito : 4.2.2+289.g2c703c73
sympy: 1.4

**Comment by mloubout** [comment]
`fwi_test_new.py` is not one of our tutorials. I suppose you modified `fwi.py` to fit what you are trying to do, can I ask what you change and what this new file is?

Concerning the convergence, this tutorial is a very simple fi step length gradient decent and will most likely need so better algorithm for more advanced models and setup.

**Comment by AlbertZhangHIT** [comment]
Actually I copy the python lines from `https://nbviewer.jupyter.org/github/devitocodes/devito/blob/master/examples/seismic/tutorials/03_fwi.ipynb` to build the script `fwi_test_new.py`. I did not modify anything.

**Comment by rhodrin** [comment]
Did you run the the jupyter notebook (`03_fwi.ipynb`) locally? Does that run ok without issue?

**Comment by FabioLuporini** [comment]
also, you should use latest devito

**Comment by AlbertZhangHIT** [comment]
Whats the latest version of devito? That I'm using is devito : 4.2.3+27.g5d925390. I tried to run the jupyter notebook `03_fwi.ipynb`, but it runs with a lot of issues. They are reported below:
```
In [3]:
The `dse` argument is deprecated. The optimization level is now controlled via the `opt` argument
The `dle` argument is deprecated. The optimization level is now controlled via the `opt` argument
Setting `opt=noop`
The `dse` argument is deprecated. The optimization level is now controlled via the `opt` argument
The `dle` argument is deprecated. The optimization level is now controlled via the `opt` argument
Setting `opt=noop`

In [12]:
/home/hao/Softwares/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: divide by zero encountered in true_divide
  if sys.path[0] == '':
/home/hao/Softwares/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in multiply
  del sys.path[0]

In [14]:
/home/hao/Softwares/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:17: RuntimeWarning: divide by zero encountered in true_divide
/home/hao/Softwares/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:20: RuntimeWarning: invalid value encountered in multiply
```
And the objective function values are 
```
Objective value is 0.000000 at iteration 1
Objective value is nan at iteration 2
Objective value is nan at iteration 3
Objective value is nan at iteration 4
Objective value is nan at iteration 5
```

**Comment by AlbertZhangHIT** [comment]
Thank you my friends. I think it's about the problem of my out-of-date version devito. Now I can close this issue.
