### ISSUE TITLE
Result is different for tutorials

### ISSUE THREAD

**Issue by pty0220** [devitocodes/devito#1415]
Hello everyone 

I am a newcomer of devito and I try to do the tutorials on SLIM's devito examples (Acoustic modeling) 
[https://slimgroup.github.io/Devito-Examples/tutorials/01_modelling/](https://slimgroup.github.io/Devito-Examples/tutorials/03_fwi/)

I write my code exactly same as the tutorial 
but the result fields looks like quite different 

Could I figure it out what is wrong?

*My computer is Win10
and I installed devito follow [Tugaonkar's post](https://medium.com/@soulfoodpst/install-devito-on-windows-a-tool-for-automatic-programming-3def3949e5c8)

This is my code 
[https://github.com/pty0220/Slicer/blob/master/acoustic_test.ipynb](https://github.com/pty0220/Slicer/blob/master/acoustic_test.ipynb)

**tutorials result look like** 

![ff](https://user-images.githubusercontent.com/42193020/88998866-f70c7800-d32d-11ea-86f6-27ff2883d0c6.PNG)

**My result look like** 

![bb](https://user-images.githubusercontent.com/42193020/88998892-04296700-d32e-11ea-954d-23b7c73ceac3.PNG)

**Comment by seaninho94** [comment]
I have the same problem. How do you solve it?

**Comment by mloubout** [comment]
model = Model(vp=v, origin=origin, shape=shape, spacing=spacing,  space_order=2, nbl=10, **bcs="damp"**)
