### ISSUE TITLE
Problem with _version.py in conda and Python 3 related to "run_command"

### ISSUE THREAD

**Issue by EricVerschuur** [devitocodes/devito#1427]
I have installed devito under miniconda environment with Python 3 under Linux.
Installation according to guidelines on the Devito install page worked out.
However, as soon as I want to import Devito in Python, it gives an error with _version.py:

  File "/home/dverschuur/devito/devito/_version.py", line 298, in git_pieces_from_vcs
    pieces["distance"] = int(count_out)  # total number of commits
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

The errors stems from the command:
count_out, rc = run_command(GITS, ["rev-list", "HEAD", "--count"],
                                    cwd=root)

So apparently, the output parameter count_out does not always have a type, but can be "None" type.

Any idea how to resolve this?

**Comment by mloubout** [comment]
What version of python 3 is it?

**Comment by mloubout** [comment]
This may also be related to some previous issue discussed on slack. Make sure that `pip` is the one from your conda environment and not from another python install. It may be called `pip3` to be the one from the conda env.

**Comment by EricVerschuur** [comment]
The python version is 3.8.5 (latest I guess).
And the pip is indeed from the devito environment:
~/miniconda3/envs/devito/bin/pip
this is version pip 20.2.1 from python 3.8

**Comment by mloubout** [comment]
What does :
```
$ git status
```
and
```
$ pip show devito
```

 says in `/home/dverschuur/devito`, it looks like the git tag is empty for some odd reason.

**Comment by EricVerschuur** [comment]
(devito) [dverschuur@awi-cloud devito]$ git status
# On branch master
nothing to commit (working directory clean)

(devito) [dverschuur@awi-cloud devito]$ pip show devito
Name: devito
Version: 4.2.3+2.g0e413ce
Summary: Finite Difference DSL for symbolic computation.
Home-page: http://www.devitoproject.org
Author: Imperial College London
Author-email: g.gorman@imperial.ac.uk
License: MIT
Location: /home/dverschuur/devito
Requires: pip, numpy, sympy, scipy, pytest, pytest-runner, flake8, nbval, cached-property, psutil, py-cpuinfo, cgen, codepy, click, codecov, pytest-cov, multidict, anytree, pyrevolve, distributed
Required-by: 

A colleague of mine has good results when using python 3.7 (instead of 3.8) on the same machine, so that may be the problem.
Im trying to do the install with 3.7 now...

**Comment by mloubout** [comment]
>Version: 4.2.3+2.g0e413ce

This is correct and should be picked up correctly, this is indeed very odd.

**Comment by mloubout** [comment]
Were you able to install 3.7 and did it fix your problem?

**Comment by EricVerschuur** [comment]
Dear Matthias
No, I could not fix the problem when shifting to 3.7. Something seems to be inconsistent still in my installation.  
But because my colleague could get it to work, I relied on his environment and gave up for myself. 
I may come back to this later when I want to work with Devito again and by that time we may have new versions...

**Comment by mloubout** [comment]
Ok thanks for the update. From the log above it looks like it is correctly installed (since it find "/home/dverschuur/devito/devito/_version.py")

Would you have the complete log of the error with the command you ran?

**Comment by EricVerschuur** [comment]
This is the command. Very simple: I only try to import devito:

(base) [dverschuur@awi-cloud ~]$ conda activate devito
(devito) [dverschuur@awi-cloud ~]$ python
Python 3.7.7 (default, May  7 2020, 21:25:33) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import devito
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=nr
    --max-age=epoch
    --min-age=epoch
    --sparse
    --no-merges
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=nr | --no-abbrev
    --abbrev-commit
    --left-right
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dverschuur/devito/devito/__init__.py", line 27, in <module>
    __version__ = get_versions()['version']
  File "/home/dverschuur/devito/devito/_version.py", line 507, in get_versions
    pieces = git_pieces_from_vcs(cfg.tag_prefix, root, verbose)
  File "/home/dverschuur/devito/devito/_version.py", line 298, in git_pieces_from_vcs
    pieces["distance"] = int(count_out)  # total number of commits
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
>>> 

And this is my environment:
(devito) [dverschuur@awi-cloud ~]$ conda list
# packages in environment at /home/dverschuur/miniconda3/envs/devito:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
anytree                   2.8.0                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
attrs                     19.3.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
ca-certificates           2020.6.24                     0  
cached-property           1.5.1                    pypi_0    pypi
certifi                   2020.6.20                py37_0  
cgen                      2020.1                   pypi_0    pypi
chardet                   3.0.4                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
cloudpickle               1.5.0                    pypi_0    pypi
codecov                   2.1.8                    pypi_0    pypi
codepy                    2019.1                   pypi_0    pypi
contexttimer              0.3.3                    pypi_0    pypi
coverage                  5.2.1                    pypi_0    pypi
dask                      2.22.0                   pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
devito                    4.2.3+2.g0e413ce           dev_0    <develop>
distributed               2.22.0                   pypi_0    pypi
flake8                    3.8.3                    pypi_0    pypi
heapdict                  1.0.1                    pypi_0    pypi
idna                      2.10                     pypi_0    pypi
importlib-metadata        1.7.0                    pypi_0    pypi
ipykernel                 5.3.4                    pypi_0    pypi
ipython                   7.17.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.17.2                   pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
jupyter-client            6.1.6                    pypi_0    pypi
jupyter-core              4.6.3                    pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
mccabe                    0.6.1                    pypi_0    pypi
more-itertools            8.4.0                    pypi_0    pypi
mpmath                    1.1.0                    pypi_0    pypi
msgpack                   1.0.0                    pypi_0    pypi
multidict                 4.7.6                    pypi_0    pypi
nbformat                  5.0.7                    pypi_0    pypi
nbval                     0.9.6                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1  
numpy                     1.19.1                   pypi_0    pypi
openssl                   1.1.1g               h7b6447c_0  
packaging                 20.4                     pypi_0    pypi
parso                     0.7.1                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pip                       20.2.1                   py37_0  
pluggy                    0.13.1                   pypi_0    pypi
prompt-toolkit            3.0.6                    pypi_0    pypi
psutil                    5.7.2                    pypi_0    pypi
ptyprocess                0.6.0                    pypi_0    pypi
py                        1.9.0                    pypi_0    pypi
py-cpuinfo                7.0.0                    pypi_0    pypi
pycodestyle               2.6.0                    pypi_0    pypi
pyflakes                  2.2.0                    pypi_0    pypi
pygments                  2.6.1                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyrevolve                 2.2                      pypi_0    pypi
pyrsistent                0.16.0                   pypi_0    pypi
pytest                    5.4.3                    pypi_0    pypi
pytest-cov                2.10.0                   pypi_0    pypi
pytest-runner             5.2                      pypi_0    pypi
python                    3.7.7                hcff3b4d_5  
python-dateutil           2.8.1                    pypi_0    pypi
pytools                   2020.3.1                 pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     19.0.2                   pypi_0    pypi
readline                  8.0                  h7b6447c_0  
requests                  2.24.0                   pypi_0    pypi
scipy                     1.5.2                    pypi_0    pypi
setuptools                49.2.1                   py37_0  
six                       1.15.0                   pypi_0    pypi
sortedcontainers          2.2.2                    pypi_0    pypi
sqlite                    3.32.3               h62c20be_0  
sympy                     1.5.1                    pypi_0    pypi
tblib                     1.7.0                    pypi_0    pypi
tk                        8.6.10               hbc83047_0  
toolz                     0.10.0                   pypi_0    pypi
tornado                   6.0.4                    pypi_0    pypi
traitlets                 4.3.3                    pypi_0    pypi
urllib3                   1.25.10                  pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
wheel                     0.34.2                   py37_0  
xz                        5.2.5                h7b6447c_0  
zict                      2.0.0                    pypi_0    pypi
zipp                      3.1.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  
(devito) [dverschuur@awi-cloud ~]$

**Comment by mloubout** [comment]
Interesting, what does
```
$ git rev-list HEAD --count
```

prints out (in devito conda env). It looks like `git` command returns something unrecognized.

**Comment by EricVerschuur** [comment]
Indeed it gives errors:
(devito) [dverschuur@awi-cloud devito]$ git rev-list HEAD --count
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=nr
    --max-age=epoch
    --min-age=epoch
    --sparse
    --no-merges
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=nr | --no-abbrev
    --abbrev-commit
    --left-right
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all

**Comment by EricVerschuur** [comment]
(devito) [dverschuur@awi-cloud devito]$ which git
/usr/bin/git

maybe git should point at something else than at /usr/bin?

**Comment by mloubout** [comment]
Mine points to `/usr/local/bin/git`

**Comment by EricVerschuur** [comment]
We have both, but the /usr/local/bin/git is from 2018, the /usr/bin/git from feb 2020. So I guess the latest is better.

**Comment by mloubout** [comment]
what is `git --version` ?

**Comment by EricVerschuur** [comment]
(devito) [dverschuur@awi-cloud miniconda3]$ git --version 
git version 1.7.1

**Comment by mloubout** [comment]
This looks like a fairly old version, could you update it?

**Comment by EricVerschuur** [comment]
Aha... the other at /usr/local/bin is version 2.19.1
I will try to redirect my PATH.

**Comment by EricVerschuur** [comment]
Problem solved !!!! 
Thanks a lot Matthias
I will ask system manager to update (or just remove) the old git stuff...

**Comment by mloubout** [comment]
Great, thanks for bearing with me, closing issue.
