### ISSUE TITLE
DEVITO_DEBUG_COMPILER deprecation FAQ modification 

### ISSUE THREAD

**Issue by jkwashbourne** [devitocodes/devito#1436]
The FAQ shows `DEVITO_DEBUG_COMPILER` as valid, but it is deprecated. Need to modify FAQ. 

Also, is it worth considering that if an environment variable with `DEVITO_` in the name is not recognized or is deprecated, we could report some output.

**Comment by FabioLuporini** [comment]
> Also, is it worth considering that if an environment variable with DEVITO_ in the name is not recognized or is deprecated, we could report some output.

I had thought about this, but people (including me) often use custom DEVITO_ env vars for other purposes (eg, I have DEVITO_HOME, DEVITO_RESULTS, ... set in my devito env) so it's not that simple

anyway, I just updated the FAQ, so I'm closing this issue. Feel free to open another one (or re-open this one) if you want to talk more about the unknown DEVITO_ env vars

**Comment by FabioLuporini** [comment]
> Also, is it worth considering that if an environment variable with DEVITO_ in the name is not recognized or is deprecated, we could report some output.

I had thought about this, but people (including me) often use custom DEVITO_ env vars for other purposes (eg, I have DEVITO_HOME, DEVITO_RESULTS, ... set in my devito env) so it's not that simple

anyway, I just updated the FAQ, so I'm closing this issue. Feel free to open another one (or re-open this one) if you want to talk more about the unknown DEVITO_ env vars
