### ISSUE TITLE
Absorbing boundary is not good

### ISSUE THREAD

**Issue by AlbertZhangHIT** [devitocodes/devito#1443]
Hi, 
I tested the absorbing boundary by puting a Ricker source at the center of square constant demo model. The number of boundary thickness `nbl` in model is set to 40. But the reflections are observed in large amplitude in snapshots. 

![abs](https://user-images.githubusercontent.com/29504198/91851191-9b2a5d00-ec13-11ea-840c-5920195cbeb6.png)

Is there other way to improve the boundary absorbility except increasing the thickness?

**Comment by rhodrin** [comment]
Hi @AlbertZhangHIT,

You could use a better model, e.g. PMLs: https://en.wikipedia.org/wiki/Perfectly_matched_layer. You can implement such models by utilizing `SubDomain`'s. See this tutorial for details: https://github.com/devitocodes/devito/blob/master/examples/userapi/03_subdomains.ipynb.

**Comment by AlbertZhangHIT** [comment]
That's cool! Thannk you.
