### ISSUE TITLE
Real dataset, receiver object

### ISSUE THREAD

**Issue by seaninho94** [devitocodes/devito#1448]
Hi, I was trying to implement a RTM and a FWI for a real dataset but I observed something strange. The receiver data that I have converted from the seg-y format have values of the order of 10^7 while the synthetic data that I create from a velocity model with devito are values much lower. What can I do to solve this?

**Comment by FabioLuporini** [comment]
this is not a devito issue, but rather a question regarding the seismic examples _built on top of_ devito. I'm therefore closing this. These sort of "higher level" questions are probably better handled on our slack directly.
