### ISSUE TITLE
ConditionalDimension: Conditions containing derivatives cause an error

### ISSUE THREAD

**Issue by EdCaunt** [devitocodes/devito#1472]
The following code:
```
import sympy as sp
from devito import Grid, Function, Eq, Operator, \
    Lt, ConditionalDimension

extent = (10., 10.)
shape = (11, 11)

grid = Grid(shape=shape, extent=extent)
x, y = grid.dimensions

f = Function(name='f', grid=grid)

cond = Lt(f.dx.evaluate, 1)

# Also
# cond = Lt(f.dx, 1)
# doesn't work (different error)

mask = ConditionalDimension(name='mask', parent=y,
                            condition=cond)

eq = Eq(f, 1, implicit_dims=mask)

op_axial = Operator(eq)
op_axial.apply()
```
Causes an error. Removing the `.evaluate` results in a similar albeit different error.

**Comment by rhodrin** [comment]
@EdCaunt Did you see my reply to the previous issue you opened? The above is not correct use of conditional dimensions.

**Comment by EdCaunt** [comment]
I didn't sorry, thought I'd forgotten to hit the create issue button on it. Looking at your reply, could I not just explicitly write out the stencil in the condition? I don't see why it shouldn't run from a ccode perspective? It seems tidier and more readable than having a second function just to store a single derivative. Also this worked prior to October 7th

**Comment by rhodrin** [comment]
Take a look at the c-codes produced.

**Comment by EdCaunt** [comment]
It no longer gets that far. You get an `AttributeError` at the python level. The prior behavior was to generate:
```
if (-f[x +1][y +1]/h_x +f[x +2][y +1]/h_x < 1)
{
    // Do thing
}
```

**Comment by FabioLuporini** [comment]
update: a potential fix is to apply `diff2sympy` to `CondiitionalDimension`'s conditions
