### ISSUE TITLE
Rework lowering of SteppingDimensions

### ISSUE THREAD

**Issue by FabioLuporini** [devitocodes/devito#1479]
There are two issues:

* Currently, index expressions involving SteppingDimensions are handled by the `iet_lower_dims` routine, which takes place right after constructing an IET from an STree. This is probably too early -- `iet_lower_dims` could be an actual iet_pass, first performing a visit of the IET to collect all uindices, and then applying the substitutions across all efuncs.

* ModuloDimensions are created from SteppingDimensions through the `build_iterators` routine, but this happens w/o using the SymbolRegistry. DerivedDimensions use instead a fairly rudimentary name cache, which should disappear in favor of the SymbolRegistry.

**Comment by Leitevmd** [comment]
I just saw this issue. I've made comments (and possible solution) at issue #1444 which (I guess) have some relation to this one.
