### ISSUE TITLE
Halo update outside time iterations

### ISSUE THREAD

**Issue by Leitevmd** [devitocodes/devito#1483]
This is another situation where halo updates are misplaced, similar to #1459, but this time outside of time-iteration loop. This is not just invalidating the halo update, but also results in compilation error, since some indices (eg. t0) passed as arguments to halo update are declared at the loop definition. 

MFE:
```
from devito import (Eq, Operator, Grid, Function, TimeFunction)

grid = Grid(shape=(10,10))
x, y = grid.dimensions
t = grid.stepping_dim

f = Function(name="f", grid=grid, space_order=4)
g = TimeFunction(name="g", grid=grid, space_order=4, time_order=2)
h = TimeFunction(name="h", grid=grid, space_order=4, time_order=2)

eqn = []
eqn.append( Eq(f, h + 1) )
eqn.append( Eq(g, f) )
eqn.append( Eq(h.forward, h + g[t,x+1,y+1] + 1) )

op = Operator(eqn)

op.apply(time_M=10)
```
Comments

* This error is also affecting PR #1406

**Comment by Leitevmd** [comment]
I think `_hoist_halospots(iet)` ([mpi.py#L69](https://github.com/devitocodes/devito/blob/master/devito/passes/iet/mpi.py#L69)) is making halo update to be misplaced (as `_merge_halospots(iet)` did in #1459).
As far as I understood, `rule0` is allowing the halo update call to be hoisted even from a time-iteration loop.
A very simple solution could be to check if candidate is a time iteration. eg.:
```
def rule0(dep, candidates):
    # E.g., `dep=W<f,[x]> -> R<f,[x-1]>` and `candidates=(time, x)` => False
    # E.g., `dep=W<f,[t1, x, y]> -> R<f,[t0, x-1, y+1]>`, `dep.cause={t,time}` and
    #       `candidates=(x,)` => True
    return (all(d in dep.distance_mapper and not d.is_Time for d in candidates) and
            not dep.cause & candidates)
```
@FabioLuporini if you could check/validate that I can submit a PR.

I have ran all mpi tests, including visco acoustic ones from PR #1406 in [viscoacoustic_example.py](https://github.com/devitocodes/devito/blob/master/examples/seismic/viscoacoustic/viscoacoustic_example.py) and it seems everything is OK now! I think this PR could finally get merged!

**Comment by FabioLuporini** [comment]
Hi, thanks for the MFE and potential patch.

Unfortunately, this patch isn't acceptable. 'Time' is no special in Devito. The concept of time is only useful in the high levels of the DSL, but within the compiler we virtually never treat it specially (there is in fact one place, but only because it's ancient code which needs to be rewritten, but anyway this has got nothing to do with MPI in general and this issue)

The examples in rule0 above are using `time` only because they're drawn from real examples.

I think you're on the right track (ie issue being rule0 in hoist_halospots) but the patch is not quite right yet

Thanks!

**Comment by Leitevmd** [comment]
I got your point! I'm sorry I don't have all these concepts clear in my mind yet.
So what if we avoid hoisting halo spots from non-halo dimensions? I could pass `loc_indices` dimensions from halo scheme entries to hoisting rules in order to check that. It makes sense?

**Comment by FabioLuporini** [comment]
> I got your point! I'm sorry I don't have all these concepts clear in my mind yet.

no probs, no worries! 

> So, what if we avoid hoisting halo spots from non-halo dimensions? I could pass loc_indices dimensions from halo scheme entries to hoisting rules in order to check that. It makes sense?

mmhh... that is too restrictive I'd say? Have you tried? Does any of the existing tests fail?

I mean, think about this situation

```
for t
  for f
    for x
      for y
        for z
          ... u[t, x-1, y, z] ... a[t, f, x, y, z] ...
```
`t` and `f` are sequential loops, while `x, y, z` are MPI-parallel loops. So, `t` is a `loc_indices` for `u`, while `f` **isn't** because it only appears in `a` but not in `u`. With your patch, what would happen? would `u`'s halo update be moved in between `t` and `f` (optimal placement) or would it remain in between `f` and `x` ? If the former, I'd be happy.

Btw, it'd be nice to add a test along these lines (a pretty advanced one to be honest) if we don't have one already...

**Comment by Leitevmd** [comment]
> mmhh... that is too restrictive I'd say? Have you tried? Does any of the existing tests fail?

With the patch I’ve proposed, there were no tests failing.

> With your patch, what would happen? would u's halo update be moved in between t and f (optimal placement) or would it remain in between f and x ? If the former, I'd be happy.

I couldn't find a way (not found any examples or similar tests) to reproduce the situation mentioned above by @FabioLuporini .That’s what I've tried, although no halo update was generated:
```
t, f = dimensions('t f')

x = SpaceDimension(name='x')
y = SpaceDimension(name='y')
z = SpaceDimension(name='z')

u = TimeFunction(name='u', shape=(3,4,4,4), space_order=4, dimensions=(t, x, y, z))
a = TimeFunction(name='a', shape=(3,3,4,4,4), space_order=4, dimensions=(t, f, x, y, z))

eqn = []
eqn.append( Eq(u, a + 1) )
eqn.append( Eq(a.forward, a + u[t,x+1,y,z]) )

op = Operator(eqn)
```

**Comment by Leitevmd** [comment]
Another situation worth mentioning is the following, which can be used for testing.

[`test_haloupdate_same_timestep`](https://github.com/devitocodes/devito/blob/master/tests/test_mpi.py#L1614) uses these equations with success:
```
eqns = [Eq(u.forward, u + v + 1.),
        Eq(v.forward, u[t+1, x, y-1] + u[t+1, x, y] + u[t+1, x, y+1])]
```
But if we use the following, halo update is placed again outside time loop:
```
eqns = [Eq(u, u + v + 1.),
        Eq(v.forward, u[t, x, y-1] + u[t, x, y] + u[t, x, y+1])]
```

**Comment by FabioLuporini** [comment]
perhaps move it to a new test rather than changing it, `test_haloupdate_same_timestep_v2` and a simple docstring about how this new test differs from the original one?

about the other post above:
> The halo update is placed in between f and x, but this is not any different from the original code's result. I'm checking what could be done to get that optimal placement you mentioned.

yes, that's the sort of test I was envisaging, great. Yep, I think we should aim for optimal placement. 

Can we add all these new tests to #1494?

**Comment by Leitevmd** [comment]
I have added the test from the last post (check last commit of #1494)

I couldn't run the operator of the other one, although [generated code](https://github.com/devitocodes/devito/files/5503203/issue1483_mfe2_code.txt) seems to be fine. The error is on the python side. I'm checking this. So for now, I could check halo update placement but wouldn't be able to run it and check numerical results. 

Anyway, I guess this test isn't mandatory to this issue, don't you agree? I thought we could move on with the PR and investigate this afterwards.

**Comment by FabioLuporini** [comment]
> Anyway, I guess this test isn't mandatory to this issue, don't you agree? I thought we could move on with the PR and investigate this afterwards.

Yes, I agree.

But could you open an issue+fix about the other one too? A python level issue doesn't sound too scary. What exactly are you seeing?

**Comment by Leitevmd** [comment]
Ok! The PR is updated with master and marked as ready for review.

I'm gonna open an issue about the error as soon as I get more confident about what is happening. It could be my script's fault. 
Here's what I'm seeing:
```
Traceback (most recent call last):
  File "mfe6.py", line 70, in <module>
    op.apply(time_M=3,f_M=3)
  File "/home/victor.leite/lde/devito-issues/devito/operator/operator.py", line 639, in apply
    args = self.arguments(**kwargs)
  File "/home/victor.leite/lde/devito-issues/devito/operator/operator.py", line 521, in arguments
    args = self._prepare_arguments(**kwargs)
  File "/home/victor.leite/lde/devito-issues/devito/operator/operator.py", line 431, in _prepare_arguments
    for k, v in p._arg_values(**kwargs).items():
  File "/home/victor.leite/lde/devito-issues/devito/types/dense.py", line 847, in _arg_values
    values = self._arg_defaults(alias=self).reduce_all()
  File "/home/victor.leite/lde/devito-issues/devito/tools/data_structures.py", line 134, in reduce_all
    return {k: self.reduce(key=k) for k in self}
  File "/home/victor.leite/lde/devito-issues/devito/tools/data_structures.py", line 134, in <dictcomp>
    return {k: self.reduce(key=k) for k in self}
  File "/home/victor.leite/lde/devito-issues/devito/tools/data_structures.py", line 128, in reduce
    return self.unique(key)
  File "/home/victor.leite/lde/devito-issues/devito/tools/data_structures.py", line 106, in unique
    raise ValueError("Unable to find unique value for key %s, candidates: %s"
ValueError: Unable to find unique value for key x_size, candidates: [4, 2]
```

**Comment by FabioLuporini** [comment]
uhmmm that's indeed quite odd. Any thoughts @mloubout ?

I guess this is still the MFE we're talking about:

```
grid = Grid(shape=(4,4,4))
x, y, z = grid.dimensions
time = grid.time_dim
t = grid.stepping_dim

f = Dimension(name='f')

u = TimeFunction(name='u', grid=grid, shape=(3,4,4,4), time_order=2, space_order=4, dimensions=(t, x, y, z))
a = TimeFunction(name='a', grid=grid, shape=(3,3,4,4,4), space_order=4, dimensions=(t, f, x, y, z))

eqn = []
eqn.append( Eq(u, a + 1) )
eqn.append( Eq(a.forward, a + u[t,x,y+1,z]) )

op = Operator(eqn)
```

**Comment by Leitevmd** [comment]
Yes this is the script I'm testing, just a minor adjustment, including time order also for `a`:
```python
grid = Grid(shape=(4,4,4))
x, y, z = grid.dimensions
t = grid.stepping_dim

f = Dimension(name='f')

u = TimeFunction(name='u', grid=grid, shape=(3,4,4,4), time_order=2, space_order=2, dimensions=(t, x, y, z))
a = TimeFunction(name='a', grid=grid, shape=(3,3,4,4,4), time_order=2, space_order=2, dimensions=(t, f, x, y, z))

eqn = [Eq(u, a + 1),
       Eq(a.forward, a + u[t,x,y+1,z])]

op = Operator(eqn)
```

**Comment by FabioLuporini** [comment]
this really looks like a minor bug in the processing of the arguments. `x_size` should be 4, as defined through the grid object

**Comment by Leitevmd** [comment]
> It could be my script's fault.

Shape argument in function must consider domain division. I was running with MPI_Comm_size of 2, so I should use `shape=(3,2,4,4)`, otherwise function gets two different arguments for x_size.
