### ISSUE TITLE
Error with wrong indices in loops

### ISSUE THREAD

**Issue by Leitevmd** [devitocodes/devito#1486]
The following MFE presents some cases in which the indexes used to access functions are not defined correctly. All these cases produce more than one time-iteration loop and that's when the error appears. 

```python
from devito import (Eq, Operator, Grid, TimeFunction)

grid = Grid(shape=(10,10))
x, y = grid.dimensions
t = grid.stepping_dim

f = TimeFunction(name="f", grid=grid, space_order=2, time_order=2) 
g = TimeFunction(name="g", grid=grid, space_order=2, time_order=2)

eqn = []
eqn.append( Eq( f.forward, f + 1 ) )

# Case 1 - Compilation error (t0 undeclared on the second loop, t0+2 should be replaced by t2)
# eqn.append( Eq( g.forward, f[t+2,x,y] ) )

# Case 2 - Segfault (t0 is declared, but t0+3 attempts to access wrong index, t0+3 should be replaced by t2)
eqn.append( Eq( g, f[t+3,x,y] ) ) 

# Case 3 - No error (t0+2 should be replaced by t2)
# eqn.append( Eq( g, f[t+2,x,y] ) )

op = Operator(eqn)

op.apply(time_M=10)
```

It seems substitutions of `SteppingDimensions` by `ModuloDimensions` in  `_lower_stepping_dims(iet)` (devito/ir/iet/scheduler.py) are being done in a misleading manner: All expressions in `iet` have their indices replaced with `uindices` (eg. `t+2` -> `t0+2`) available in the first iteration tree, which in these examples is the first time-iteration loop. That way, when we get to the second time-iteration loop, indices that were supposed to be replaced (eg. `t+2` -> `t2`) are not found because they have already been replaced (eg. `t+2` -> `t0+2`) and so they remain that way in the code, resulting in compilation or execution errors. This is because the second time-iteration loop may not even have that `t0` indice (Case 1) or if it has `t0` it can attempt to access wrong index (Case 2) since indexes are miscalculated (eg. `t0+2 != t2`, because `t0 = (time)%(3)`, `t2 = (time+2)%(3)`, so `t0+2` could reach 4, out-of-bounds, as soon as t0==2). Also, that could even not produce any errors at all, but still mess up the numerical result (Case 3).

**Comment by Leitevmd** [comment]
I think we can solve this issue changing `_lower_stepping_dims(iet)` (devito/ir/iet/scheduler.py) definition by making substitutions to occur only at child expressions of each iteration at a time, thus building a mapper which further transforms the entire `iet`. I've tested this and got no problems of declaration missing or segfaults anymore. All indices in expressions are in accordance with its iteration loop.

```python
def _lower_stepping_dims(iet):
    imapper = {}
    for i in FindNodes(Iteration).visit(iet):
        if not i.uindices:
            # Be quick: avoid uselessy reconstructing nodes
            continue
        # In an expression, there could be `u[t+1, ...]` and `v[t+1, ...]`, where
        # `u` and `v` are TimeFunction with circular time buffers (save=None) *but*
        # different modulo extent. The `t+1` indices above are therefore conceptually
        # different, so they will be replaced with the proper ModuloDimension through
        # two different calls to `xreplace`
        mindices = [d for d in i.uindices if d.is_Modulo]
        groups = as_mapper(mindices, lambda d: d.modulo)
        for k, v in groups.items():
            mapper = {d.origin: d for d in v}
            rule = lambda i: i.function.is_TimeFunction and i.function._time_size == k
            replacer = lambda i: xreplace_indices(i, mapper, rule)
            # iet = XSubs(replacer=replacer).visit(iet) 
            imapper[i] = XSubs(replacer=replacer).visit(i)
            
    return Transformer(imapper).visit(iet)
    
```

**Comment by FabioLuporini** [comment]
yes, this looks about right. 

nitpicking: `imapper` -> `subs` (for maximum code homogeneity -- when the name 'mapper' is already taken, the next favourite one to keep track of substitutions is 'subs' )

could you open a PR plus test(s) ? please, update the tests so as to `assert` against some expected values

**Comment by mloubout** [comment]
```
# Case 1 - Compilation error (t0 undeclared on the second loop, t0+2 should be replaced by t2)
# eqn.append( Eq( g.forward, f[t+2,x,y] ) )

# Case 2 - Segfault (t0 is declared, but t0+3 attempts to access wrong index, t0+3 should be replaced by t2)
eqn.append( Eq( g, f[t+3,x,y] ) ) 

# Case 3 - No error (t0+2 should be replaced by t2)
# eqn.append( Eq( g, f[t+2,x,y] ) )
```

But these are all invalid and should throw an error not be converted.

 For `time_order=2`, and any given `time` index, only three indices are defined, `t-1, t, t+1` every other is either already forgotten or doesn't exist yet. What you are infering from the C code is not what you think it is and comes from the shift in indices to avoid computing modulo on negative values (`t- 1` can be negative which would be problematic but `(t-1)%3  = (t+2)%3` so we compute the latest).

**Comment by FabioLuporini** [comment]
copy-pasting example posted on Slack by @mloubout for future reference

consider
```
f = TimeFunction(time_order=2)
g = TimeFunction(time_order=2)
Eq(f, time)
Eq(g, f[t-2])
```
Then the corect values for `f` are `1,2,3,4…..`  and for `g` are `0, 0, 1,2,3,4,….` but if you replace f[t-2] by f[t2] then that’s not what you get. The fact that the modulo index makes it a non-segfault index doesn’t mean it’s a valid index expression-wise (edited) 

also this is related to: https://github.com/devitocodes/devito/issues/602 (which I've just updated with further info)

**Comment by Leitevmd** [comment]
Sorry for being so wordy!

I understand that t+2 (or t+3), with a time dimension of 2, does not have a right meaning, but again if loop stepping indices are assigned like that, shouldn't expressions do the same? The only case I could reproduce such behavior (two time loops) without using out of bound indices was that one with an intermediary non-time function, which again I'm not certain if it has any meaningful application (I suppose not). I also understand that avoiding these situations by throwing exceptions would do the job, although I think maybe this could still be a flaw in the code. I’m sorry if I missed something from your messages. I’m going to review that more carefully.

The patch I've proposed makes expressions to be built in accordance with their loops and by doing this, it avoids critical errors like segfault and declaration missing. I could assert values from a time marching operator, even with these out of bound indices, since we know they would point to some time buffer (due to %(3)). And yes, I understand that would not have the right meaning for any real application.

The only tests that are failing with the proposed patch are:
* tests/test_dimension.py::TestBufferedDimension::test_multi_buffer
* tests/test_dimension.py::TestBufferedDimension::test_multi_buffer_long_time

I noticed these are the only tests which use `save=Buffer(N)`, with N > 2 (With N=2 tests have passed, eg.: tests/test_save.py::test_buffer_api).
I couldn't find the reason yet (still look into that), but with `save=Buffer(N)` for with N > 2, indices are not replaced as expected, and parameter `t` gets no value. See code produced and apply error, below:

```C++
for (int time = time_m, t0 = (time + 1)%(2), t1 = (time)%(3); time <= time_M; time += 1, t0 = (time + 1)%(2), t1 = (time)%(3))
  {
    struct timeval start_section0, end_section0;
    gettimeofday(&start_section0, NULL);
    /* Begin section0 */
    for (int x = x_m; x <= x_M; x += 1)
    {
      #pragma omp simd aligned(f,g:64)
      for (int y = y_m; y <= y_M; y += 1)
      {
        f[t + 1][x + 1][y + 1] = 1;
        g[t1][x + 1][y + 1] = f[t + 1][x + 1][y + 1];
      }
    }
    /* End section0 */
    gettimeofday(&end_section0, NULL);
    timers->section0 += (double)(end_section0.tv_sec-start_section0.tv_sec)+(double)(end_section0.tv_usec-start_section0.tv_usec)/1000000;
  }
```

```
Traceback (most recent call last):
  File "mfe3.py", line 44, in <module>
    op.apply(time_M=3)
  File "/home/victor.leite/lde/devito-issues/devito/operator/operator.py", line 640, in apply
    args = self.arguments(**kwargs)
  File "/home/victor.leite/lde/devito-issues/devito/operator/operator.py", line 526, in arguments
    raise ValueError("No value found for parameter %s" % p.name)
ValueError: No value found for parameter t

**Comment by Leitevmd** [comment]
This is a draft for the test I've mentioned above.
```python
    @pytest.mark.parametrize('expr,result', [
        ('[Eq(g, f[t+1, x, y])]',[(10.,11.,9.)]),
        ('[Eq(g, f[t+2, x, y])]',[(11.,9.,10.)]),
        ('[Eq(g, f[t+3, x, y])]',[(9.,10.,11.)]),
        ('[Eq(g.forward, f[t+2, x, y])]',[(10.,11.,9.)]),
    ])
    def test_lower_stepping_dimentions(self, expr, result):

        grid = Grid(shape=(4,4))
        x, y = grid.dimensions
        t = grid.stepping_dim

        f = TimeFunction(name="f", grid=grid, space_order=2, time_order=2) 
        g = TimeFunction(name="g", grid=grid, space_order=2, time_order=2)
        
        f.data[:] = g.data[:] = 0.

        op = Operator([Eq(f.forward, f + 1)] + eval(expr))

        exprs = FindNodes(Expression).visit(op)
        assert isinstance(exprs[0].expr.lhs.indices[0],ModuloDimension)
        assert isinstance(exprs[0].expr.rhs.args[1].indices[0],ModuloDimension)
        assert isinstance(exprs[1].expr.lhs.indices[0],ModuloDimension)
        assert isinstance(exprs[1].expr.rhs.indices[0],ModuloDimension)

        op.apply(time=10)

        result = [(9.,10.,11.)] + result

        for i in range(3):
            assert np.all(f.data[i, :, :] == result[0][i])
            assert np.all(g.data[i, :, :] == result[1][i])
```

**Comment by FabioLuporini** [comment]
I admit I haven't touched the Buffer stuff in a while, but it feels like you're on the right track?

> I guess this doesn't invalidate this issue. E.g.: If loop stepping indices are assigned like that, shouldn't expressions do the same? I’m sorry if I missed something here. I’m going to review that more carefully.

I do agree. Though I think that what @mloubout was saying is that we shouldn't actually get that far in compilation. But yes, this is a symptom, as you correctly pointed out, that something is off

> We could move forward with that MFE using an intermediary (non-time dependent) function, which is the only case I could reproduce such behavior (two time loops) without using out of bound indices.

I think it boils down to whether the MFEs are fundamentally different or they're just triggering the very same bug through different constructs. In the former case, I'd like to have all the MFEs; in the latter case, just one would be fine.

I think you were on the right track with the initial patch, but yeah, we need to figure out why the Buffer tests would now break

Thanks!

**Comment by Leitevmd** [comment]
> I think it boils down to whether the MFEs are fundamentally different or they're just triggering the very same bug through different constructs. In the former case, I'd like to have all the MFEs; in the latter case, just one would be fine.

I think we're dealing with the latter: we're triggering the same situation from different constructs. I think the problem is the code does not expect more than one iteration at the same level with different modulo dimensions. Those MFEs make it happen with time.

> I think you were on the right track with the initial patch, but yeah, we need to figure out why the Buffer tests would now break

That was actually my fault. When I change the flow of transformations to prevent them all to get the whole iet, I must assure the inner loop transformations remain cumulative, and not with respect to the same input, as I did before. It would also break also with different `time_order` values in functions of the same operator.

That fixes it:
```python
def _lower_stepping_dims(iet):
    subs = {}
    for i in FindNodes(Iteration).visit(iet):
        if not i.uindices:
            # Be quick: avoid uselessy reconstructing nodes
            continue
        mindices = [d for d in i.uindices if d.is_Modulo]
        groups = as_mapper(mindices, lambda d: d.modulo)
        i_org = i
        for k, v in groups.items():
            mapper = {d.origin: d for d in v}
            rule = lambda i: i.function.is_TimeFunction and i.function._time_size == k
            replacer = lambda i: xreplace_indices(i, mapper, rule)
            subs[i] = XSubs(replacer=replacer).visit(i)
        #     i = XSubs(replacer=replacer).visit(i)
        # subs[i_org] = i

    return Transformer(subs).visit(iet)
```

**Comment by Leitevmd** [comment]
> I think it boils down to whether the MFEs are fundamentally different or they're just triggering the very same bug through different constructs. In the former case, I'd like to have all the MFEs; in the latter case, just one would be fine.

I think we're dealing with the latter: we're triggering the same situation from different constructs. I think the problem is the current code does not expect more than one iteration loop at the same level with different modulo dimensions. Those MFEs make it happen with time.

> I think you were on the right track with the initial patch, but yeah, we need to figure out why the Buffer tests would now break

That was actually my fault. When I change the flow of transformations to prevent them all to get the whole iet, I must assure the inner loop transformations remain cumulative, and not with respect to the same input, as I did before. It would also break with different `time_order` values in functions of the same operator.

That fixes it:
```python
def _lower_stepping_dims(iet):
    subs = {}
    for i in FindNodes(Iteration).visit(iet):
        if not i.uindices:
            # Be quick: avoid uselessy reconstructing nodes
            continue
        mindices = [d for d in i.uindices if d.is_Modulo]
        groups = as_mapper(mindices, lambda d: d.modulo)
        i_org = i
        for k, v in groups.items():
            mapper = {d.origin: d for d in v}
            rule = lambda i: i.function.is_TimeFunction and i.function._time_size == k
            replacer = lambda i: xreplace_indices(i, mapper, rule)
            i = XSubs(replacer=replacer).visit(i)
        subs[i_org] = i

    return Transformer(subs).visit(iet)
```

**Comment by Leitevmd** [comment]
@FabioLuporini, I opened the draft PR #1504 for your review.

The added test would result in an assertion error like the one shown below without this correction:
```
E           assert {t0, t0 + 1} == {t1, t0}
E             Extra items in the left set:
E             t0 + 1
E             Extra items in the right set:
E             t1
E             Full diff:
E             - {t1, t0}
E             + {t0, t0 + 1}
```
