### ISSUE TITLE
ModuleNotFoundError: No module named 'cgen'

### ISSUE THREAD

**Issue by ShuaiDa** [devitocodes/devito#1508]
When I install devito under the instructions and open a jupyter notebook to learn the `02_apply.ipynb` in `examples/userapi`.

> from devito import Grid, TimeFunction, Eq, Operator
> grid = Grid(shape=(4, 4))
> u = TimeFunction(name='u', grid=grid, save=3)
> op = Operator(Eq(u.forward, u + 1))

The error is

> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-1-6f586e2ec3b8> in <module>
> ----> 1 from devito import Grid, TimeFunction, Eq, Operator
>       2 
>      3 grid = Grid(shape=(4, 4))
>      4 u = TimeFunction(name='u', grid=grid, save=3)
>      5 op = Operator(Eq(u.forward, u + 1))
> ~/devito/devito/__init__.py in <module>
>       2 
>      3 # Import the global `configuration` dict
> ----> 4 from devito.parameters import *  # noqa
>      5 
>     6 # API imports
> ~/devito/devito/parameters.py in <module>
>      6 
>      7 from devito.logger import warning
>  ----> 8 from devito.tools import Signer, filter_ordered
>      9 
>     10 __all__ = ['configuration', 'init_configuration', 'print_defaults', 'print_state',
> ~/devito/devito/tools/__init__.py in <module>
> ----> 1 from devito.tools.utils import *  # noqa
>       2 from devito.tools.abc import *  # noqa
>      3 from devito.tools.algorithms import *  # noqa
>      4 from devito.tools.data_structures import *  # noqa
>      5 from devito.tools.memoization import *  # noqa
> ~/devito/devito/tools/utils.py in <module>
>      9 import numpy as np
>     10 import sympy
> ---> 11 from cgen import dtype_to_ctype as cgen_dtype_to_ctype
>     12 
>     13 __all__ = ['prod', 'as_tuple', 'is_integer', 'generator', 'grouper', 'split', 'roundm',
> ModuleNotFoundError: No module named 'cgen'

Then I check whether I have installed 'cgen', the result is

> packages in environment at /home/sd/anaconda3/envs/devito:
> Name        Version        Build              Channel
> cgen           2020.1         pypi_0            pypi

I try to install devito in WSL and Ubuntu systems. After I install devito and run the jupyter notebook in examples, the results are both ` ModuleNotFoundError: No module named 'cgen'`.

How should I fix this bug?

**Comment by FabioLuporini** [comment]
if you rather try this

```
from devito import Grid, TimeFunction, Eq, Operator
grid = Grid(shape=(4, 4))
u = TimeFunction(name='u', grid=grid, save=3)
op = Operator(Eq(u.forward, u + 1))
```

in a standard python file (ie no jupyter notebook) does it work instead?

did you remember to activate the conda environment? each time you open a new terminal you will have to activate it

**Comment by ShuaiDa** [comment]
Each time I use `source activate devito` to activate the conda environment.

I tried the codes in a standard python file (`testinstallation.py`) in spyder and put the .py file in the `/home/sd/devito/devito` directory , the error is 

> ImportError: cannot import name 'Grid' from 'devito' (unknown location)

When I put the `testinstallation.py` file in the '/home/sd/devito' derectory, the error is

> ModuleNotFoundError: No module named 'cgen'

**Comment by georgebisbas** [comment]
Can you try in your terminal to run:

```
source activate devito
python *path-to*/testinstallation.py
```
If I remember well, spyder needs some additional configuration to be made.

**Comment by ShuaiDa** [comment]
Thanks. 
I try the `testinstallation.py` in terminal and vs code, it runs successfully.

**Comment by georgebisbas** [comment]
No problem. I will procees in closing this issue. Feel free to reopen or contact us in our [Slack channel](https://join.slack.com/t/devitocodes/shared_invite/zt-gtd2yxj9-Y31YKk_7lr9AwfXeL2iMFg) if you experience any more problems.
