### ISSUE TITLE
`div`, `grad` etc. should accept `shift` as a `tuple`

### ISSUE THREAD

**Issue by rhodrin** [devitocodes/devito#1554]
The tensor operators `div`, `grad` and `curl` currently only accept `shift` as a single `float`. Since the staggering can be different in each dimension however they should also be able to accept a `tuple` of `float` of length `dims`.

See, e.g., [here](https://github.com/devitocodes/devito/blob/1802de464921b2ca225ec5e18e1f7935a9fbddab/devito/types/tensor.py#L305).

**Comment by Leitevmd** [comment]
Hi @rhodrin, is someone already working on that? I could work on it
