### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by mloubout** [devitocodes/devito#1565]
Requirement files splitting breaks `pip` install. mpi and gpu extra can't be installed via pip since they are not in `extras` anymore. Need to either:

- be reverted to `requirments` and `requirements-optional`
- Fix setup.py to have more install cases

**Comment by FabioLuporini** [comment]
I suggest the latter, as the former option would interfere with Dockerfile.nvidia IIRC

**Comment by FabioLuporini** [comment]
fixed by #1847
