### ISSUE TITLE
fwi_gradient stuck in codepy/jit.py

### ISSUE THREAD

**Issue by zxliying** [devitocodes/devito#1566]
Hello,
        I have installed the devito on centos 7 in conda environment. However, it stucked when running tutorial 03_fwi.ipynb.  The  fwi_gradient funtion stucked in codepy/jit.py. Cache samed locked, but why. Can anyone help me find out the problem?
Best,
Phx 

---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-13-2994f1c10000> in <module>
      1 # Compute gradient of initial model
----> 2 ff, update = fwi_gradient(model0.vp)
      3 assert np.isclose(ff, 57283, rtol=1e0)

<ipython-input-12-acbc96999f98> in fwi_gradient(vp_in)
     31         compute_residual(residual, d_obs, d_syn)
     32 
---> 33         objective += .5*norm(residual)**2
     34         solver.gradient(rec=residual, u=u0, vp=vp_in, grad=grad)
     35 

~/.local/lib/python3.9/site-packages/devito/parameters.py in wrapper(*args, **kwargs)
    260                 configuration[k] = v
    261             try:
--> 262                 result = func(*args, **kwargs)
    263             finally:
    264                 for k, v in self.params.items():

~/.local/lib/python3.9/site-packages/devito/builtins/arithmetic.py in norm(f, order)
     36                          [dv.Inc(s, Abs(Pow(p, order))), dv.Eq(mr.n[0], s)],
     37                          name='norm%d' % order)
---> 38         op.apply(**kwargs)
     39 
     40     v = Pow(mr.v, 1/order)

~/.local/lib/python3.9/site-packages/devito/operator/operator.py in apply(self, **kwargs)
    656         arg_values = [args[p.name] for p in self.parameters]
    657         try:
--> 658             cfunction = self.cfunction
    659             with self._profiler.timer_on('apply', comm=args.comm):
    660                 cfunction(*arg_values)

~/.local/lib/python3.9/site-packages/devito/operator/operator.py in cfunction(self)
    571         """The JIT-compiled C function as a ctypes.FuncPtr object."""
    572         if self._lib is None:
--> 573             self._jit_compile()
    574             self._lib = self._compiler.load(self._soname)
    575             self._lib.name = self._soname

~/.local/lib/python3.9/site-packages/devito/operator/operator.py in _jit_compile(self)
    556         if self._lib is None:
    557             with self._profiler.timer_on('jit-compile'):
--> 558                 recompiled, src_file = self._compiler.jit_compile(self._soname,
    559                                                                   str(self.ccode))
    560 

~/.local/lib/python3.9/site-packages/devito/compiler.py in jit_compile(self, soname, code)
    316         with warnings.catch_warnings():
    317             warnings.simplefilter('ignore')
--> 318             _, _, _, recompiled = compile_from_string(self, target, code, src_file,
    319                                                       cache_dir=cache_dir, debug=debug,
    320                                                       sleep_delay=sleep_delay)

~/miniconda3/envs/devito/lib/python3.9/site-packages/codepy/jit.py in compile_from_string(toolchain, name, source_string, source_name, cache_dir, debug, wait_on_error, debug_recompile, object, source_is_binary, sleep_delay)
    392         # Variable 'lock_m' is used for no other purpose than
    393         # to keep lock manager alive.
--> 394         lock_m = CacheLockManager(cleanup_m, cache_dir, sleep_delay)  # noqa
    395 
    396         hex_checksum = calculate_hex_checksum()

~/miniconda3/envs/devito/lib/python3.9/site-packages/codepy/jit.py in __init__(self, cleanup_m, cache_dir, sleep_delay)
    122 
    123                 from time import sleep
--> 124                 sleep(sleep_delay)
    125 
    126                 attempts += 1

KeyboardInterrupt:

**Comment by mloubout** [comment]
Does the simple examples run fine, like `python examples/seismic/acoustic/acoustic_example.py` ?

**Comment by zxliying** [comment]
> Does the simple examples run fine, like `python examples/seismic/acoustic/acoustic_example.py` ?
The simple examples run fine.

python examples/seismic/acoustic/acoustic_example.py
Operator `initdamp` ran in 0.06 s
Operator `pad_vp` ran in 0.01 s
Applying Forward
Operator `Forward` ran in 4.23 s

**Comment by mloubout** [comment]
I don't  remember if we fully support Python 3.9 yet, but I would recommend Python 3.6-3.8 for now (you are running 3.9)

**Comment by zxliying** [comment]
> I don't remember if we fully support Python 3.9 yet, but I would recommend Python 3.6-3.8 for now (you are running 3.9)

Thanks mloubout. I downgrade python by using "conda install python=3.6". The problem still exists.
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-14-2994f1c10000> in <module>
      1 # Compute gradient of initial model
----> 2 ff, update = fwi_gradient(model0.vp)
      3 assert np.isclose(ff, 57283, rtol=1e0)

<ipython-input-13-acbc96999f98> in fwi_gradient(vp_in)
     31         compute_residual(residual, d_obs, d_syn)
     32 
---> 33         objective += .5*norm(residual)**2
     34         solver.gradient(rec=residual, u=u0, vp=vp_in, grad=grad)
     35 

~/devito/devito/parameters.py in wrapper(*args, **kwargs)
    260                 configuration[k] = v
    261             try:
--> 262                 result = func(*args, **kwargs)
    263             finally:
    264                 for k, v in self.params.items():

~/devito/devito/builtins/arithmetic.py in norm(f, order)
     36                          [dv.Inc(s, Abs(Pow(p, order))), dv.Eq(mr.n[0], s)],
     37                          name='norm%d' % order)
---> 38         op.apply(**kwargs)
     39 
     40     v = Pow(mr.v, 1/order)

~/devito/devito/operator/operator.py in apply(self, **kwargs)
    656         arg_values = [args[p.name] for p in self.parameters]
    657         try:
--> 658             cfunction = self.cfunction
    659             with self._profiler.timer_on('apply', comm=args.comm):
    660                 cfunction(*arg_values)

~/devito/devito/operator/operator.py in cfunction(self)
    571         """The JIT-compiled C function as a ctypes.FuncPtr object."""
    572         if self._lib is None:
--> 573             self._jit_compile()
    574             self._lib = self._compiler.load(self._soname)
    575             self._lib.name = self._soname

~/devito/devito/operator/operator.py in _jit_compile(self)
    557             with self._profiler.timer_on('jit-compile'):
    558                 recompiled, src_file = self._compiler.jit_compile(self._soname,
--> 559                                                                   str(self.ccode))
    560 
    561             elapsed = self._profiler.py_timers['jit-compile']

~/devito/devito/compiler.py in jit_compile(self, soname, code)
    318             _, _, _, recompiled = compile_from_string(self, target, code, src_file,
    319                                                       cache_dir=cache_dir, debug=debug,
--> 320                                                       sleep_delay=sleep_delay)
    321 
    322         return recompiled, src_file

~/miniconda3/envs/devito/lib/python3.6/site-packages/codepy/jit.py in compile_from_string(toolchain, name, source_string, source_name, cache_dir, debug, wait_on_error, debug_recompile, object, source_is_binary, sleep_delay)
    392         # Variable 'lock_m' is used for no other purpose than
    393         # to keep lock manager alive.
--> 394         lock_m = CacheLockManager(cleanup_m, cache_dir, sleep_delay)  # noqa
    395 
    396         hex_checksum = calculate_hex_checksum()

~/miniconda3/envs/devito/lib/python3.6/site-packages/codepy/jit.py in __init__(self, cleanup_m, cache_dir, sleep_delay)
    122 
    123                 from time import sleep
--> 124                 sleep(sleep_delay)
    125 
    126                 attempts += 1

KeyboardInterrupt:

**Comment by mloubout** [comment]
Ok thanks for trying will double check

**Comment by FabioLuporini** [comment]
@zxliying perhaps the cache is in an inconsistent state for whatever reason.

From the root devito directory, can you execute

```python scripts/clear_devito_cache.py```

and then try again?

**Comment by zxliying** [comment]
> @zxliying perhaps the cache is in an inconsistent state for whatever reason.
> 
> From the root devito directory, can you execute
> 
> `python scripts/clear_devito_cache.py`
> 
> and then try again?

Thanks FabioLuporini, your solution really solved my problem. Thank you very much!

**Comment by georgebisbas** [comment]
Issue resolved. Closing this issue. Feel free to reopen if needed.
