### ISSUE TITLE
There is currently no testing for derivatives evaluated at non-standard positions

### ISSUE THREAD

**Issue by EdCaunt** [devitocodes/devito#1601]
We currently only test  `.dx(x0=x)`, `.dx(x0=x+h_x/2)` and `.dx(x0=x-h_x/2)`. We should probably also test other offsets (`x+h_x/4` etc).

**Comment by mloubout** [comment]
That's because this would lead to invalid indices, only cartesian and half node positions are valid

**Comment by EdCaunt** [comment]
In the sense that it's not possible, or that it doesn't have a practical use?

**Comment by mloubout** [comment]
Is not possible with current implementation, and doesn't really have a use neither.
