### ISSUE TITLE
how to run examples from command line properly?

### ISSUE THREAD

**Issue by ahadji05** [devitocodes/devito#1621]
Hi devito support,

I'm working from a Ubuntu-20 laptop,
I have downloaded the devito code from GitHub as you suggest:$ `git clone https://github.com/devitocodes/devito.git` ,
and before attempt to run anything, I installed in a new python virtual environment all the necessary dependencies according to file `requirements.txt`  to make sure that no dependency issues would arise!

Instead of jupyter notebook, I would like to run the example from the command line!
For example, I tried to run the script `acoustic_example.py` which is located in the directory: devito/examples/seismic/acoustic/

I initially attempted to run __init__.py as: $ `python __init__.py`
but that results in an **ImportError**:

```
Traceback (most recent call last):
  File "__init__.py", line 1, in <module>
    from .operators import *  # noqa
ImportError: attempted relative import with no known parent package
```

Then, tried directly to run the script `acoustic_example.py` as: $ `python acoustic_example.py`
which result in a **ModuleNotFoundError**: 

```
Traceback (most recent call last):
  File "acoustic_example.py", line 4, in <module>
    from devito.logger import info
ModuleNotFoundError: No module named 'devito'
```

I tried to make it work by appending in the system path the directory devitio, like this:
sys.path.append('path/to/devito') ,
but neither that worked!

At first, is it possible to run tests/examples from the command line?, and if yes, 
what is the recommended way to do it?

Andreas

**Comment by mloubout** [comment]
Did you install devito as per the documentation or only cloned it and install the dependencies?

**Comment by ahadji05** [comment]
No, I didn't that was the problem in that case.
Thanks!

Though I face a **CompileError** issue now!

According to the documentation, I installed the devito package using:
`pip install git+https://github.com/devitocodes/devito.git`
(I could not use the option `--user` because I am using a virtual environment and when I tried it I got this error:
`ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.`)

In any way, that installation seemed to work successfully, 
for example, if I do a `pip list` I see devito on the packages list,
and also if I open the python interpreter I can execute without issues the commands:
```
>>> from devito import Grid
>>> from devito import TimeFunction
>>> from devito import Eq
>>> from devito import Operator
>>> from devito import solve
>>> grid = Grid(shape=(10, 10))
>>> f = TimeFunction(name='f', grid=grid, space_order=2)
>>> eqn = Eq(f.dt, 0.5 * f.laplace)
>>> op = Operator(Eq(f.forward, solve(eqn, f.forward)))
```

however, when I try to run the experiment for let's say 10 time-steps I get the following **CompileError**:

```
>>> nt=10
>>> op(t=nt)
/home/ahadji05/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/ahadji05/anaconda3/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib/../lib/Scrt1.o: in function `_start':
/home/rdonnelly/mc/conda-bld/compilers_linux-64_1534865402226/work/.build/src/glibc-2.12.2/csu/../sysdeps/x86_64/elf/start.S:99: undefined reference to `main'
collect2: error: ld returned 1 exit status
FAILED compiler invocation:/home/ahadji05/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/ahadji05/anaconda3/include -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/ahadji05/anaconda3/lib -Wl,-rpath-link,/home/ahadji05/anaconda3/lib -L/home/ahadji05/anaconda3/lib /tmp/devito-jitcache-uid1000/6fd23168cb2011ba005f81ef54a934b23162f0b5.c -lm -o /tmp/devito-jitcache-uid1000/6fd23168cb2011ba005f81ef54a934b23162f0b5.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ahadji05/devito_venv/lib/python3.7/site-packages/devito/operator/operator.py", line 577, in __call__
    return self.apply(**kwargs)
  File "/home/ahadji05/devito_venv/lib/python3.7/site-packages/devito/operator/operator.py", line 648, in apply
    cfunction = self.cfunction
  File "/home/ahadji05/devito_venv/lib/python3.7/site-packages/devito/operator/operator.py", line 563, in cfunction
    self._jit_compile()
  File "/home/ahadji05/devito_venv/lib/python3.7/site-packages/devito/operator/operator.py", line 549, in _jit_compile
    str(self.ccode))
  File "/home/ahadji05/devito_venv/lib/python3.7/site-packages/devito/arch/compiler.py", line 320, in jit_compile
    sleep_delay=sleep_delay)
  File "/home/ahadji05/devito_venv/lib/python3.7/site-packages/codepy/jit.py", line 433, in compile_from_string
    toolchain.build_extension(ext_file, source_paths, debug=debug)
  File "/home/ahadji05/devito_venv/lib/python3.7/site-packages/codepy/toolchain.py", line 210, in build_extension
    raise CompileError("module compilation failed")
codepy.CompileError: module compilation failed

```

**Comment by FabioLuporini** [comment]
that error trace doesn't look complete. Does it not also provide the specific compilation error message?

**Comment by ahadji05** [comment]
Hi Fabio,

why doesn't this error trace look complete? this is the whole error message I got when I tried to execute the last command
`op(t=10)`

**Comment by georgebisbas** [comment]
Hi Andrea,
can you try running with DEVITO_ARCH=gcc and
can you paste the `/tmp/devito-jitcache-uid1000/6fd23168cb2011ba005f81ef54a934b23162f0b5.c`
?

**Comment by ahadji05** [comment]
Hi George,

running `DEVITO_ARCH=gcc` is executed with no issue!

however, I cannot find the file you mention..
what is this file ?

**Comment by georgebisbas** [comment]
Please try running `DEVITO_ARCH=gcc python examples/seismic/acoustic/acoustic_example.py`
The file I mention is the generated c code located.
try:
`cat /tmp/devito-jitcache-uid1000/6fd23168cb2011ba005f81ef54a934b23162f0b5.c`

**Comment by ahadji05** [comment]
Hi George,

I found the file, I don't know what kind of typo I did before and couldn't find it...
here it is:

(devito_venv) (base) ahadji05@ahadji05-UX330UAR:~$ cat /tmp/devito-jitcache-uid1000/6fd23168cb2011ba005f81ef54a934b23162f0b5.c 
#define _POSIX_C_SOURCE 200809L
#define START_TIMER(S) struct timeval start_ ## S , end_ ## S ; gettimeofday(&start_ ## S , NULL);
#define STOP_TIMER(S,T) gettimeofday(&end_ ## S, NULL); T->S += (double)(end_ ## S .tv_sec-start_ ## S.tv_sec)+(double)(end_ ## S .tv_usec-start_ ## S .tv_usec)/1000000;

#include "stdlib.h"
#include "math.h"
#include "sys/time.h"
#include "xmmintrin.h"
#include "pmmintrin.h"

struct dataobj
{
  void *restrict data;
  int * size;
  int * npsize;
  int * dsize;
  int * hsize;
  int * hofs;
  int * oofs;
} ;

struct profiler
{
  double section0;
} ;


int Kernel(const float dt, struct dataobj *restrict f_vec, const float h_x, const float h_y, const int time_M, const int time_m, const int x_M, const int x_m, const int y_M, const int y_m, struct profiler * timers)
{
  float (*restrict f)[f_vec->size[1]][f_vec->size[2]] __attribute__ ((aligned (64))) = (float (*)[f_vec->size[1]][f_vec->size[2]]) f_vec->data;

  /* Flush denormal numbers to zero in hardware */
  _MM_SET_DENORMALS_ZERO_MODE(_MM_DENORMALS_ZERO_ON);
  _MM_SET_FLUSH_ZERO_MODE(_MM_FLUSH_ZERO_ON);

  for (int time = time_m, t0 = (time)%(2), t1 = (time + 1)%(2); time <= time_M; time += 1, t0 = (time)%(2), t1 = (time + 1)%(2))
  {
    /* Begin section0 */
    START_TIMER(section0)
    for (int x = x_m; x <= x_M; x += 1)
    {
      #pragma omp simd aligned(f:32)
      for (int y = y_m; y <= y_M; y += 1)
      {
        float r5 = -1.0F*f[t0][x + 2][y + 2];
        f[t1][x + 2][y + 2] = dt*((r5 + 5.0e-1F*(f[t0][x + 2][y + 1] + f[t0][x + 2][y + 3]))/((h_y*h_y)) + (r5 + 5.0e-1F*(f[t0][x + 1][y + 2] + f[t0][x + 3][y + 2]))/((h_x*h_x)) + f[t0][x + 2][y + 2]/dt);
      }
    }
    STOP_TIMER(section0,timers)
    /* End section0 */
  }

  return 0;
}

**Comment by georgebisbas** [comment]
Did you try this ?
`Please try running DEVITO_ARCH=gcc python examples/seismic/acoustic/acoustic_example.py`

**Comment by ahadji05** [comment]
yes, just tried it and it seems that this solved the issue!

```
(devito_venv) (base) ahadji05@ahadji05-UX330UAR:~/devito/examples/seismic/acoustic$ DEVITO_ARCH=gcc python acoustic_example.py 
Operator `initdamp` ran in 0.02 s
Operator `pad_vp` ran in 0.01 s
Applying Forward
Operator `Forward` ran in 2.77 s

```

**Comment by ahadji05** [comment]
thank you very much!!

**Comment by georgebisbas** [comment]
No problem, I am closing this issue now, feel free to reopen or directly contact us in Devito slack channel.
