### ISSUE TITLE
Source injection/receiver interpolation fail with MPI+OpenACC

### ISSUE THREAD

**Issue by ccuetom** [devitocodes/devito#1641]
Running an operator with either source injection or receiver interpolation using OpenACC and MPI domain decomposition results in a crash when the number of ranks becomes large.

In the 2D iso-acoustic example, this problem seems to appear for any domain size when `nranks >= 3`.

The problem seems to get solved when changing:

```
#pragma acc parallel ....
```

to:

```
#pragma acc parallel .... if (p_src_M - p_src_m >= 0)
```

around the injection and interpolation.

**Comment by FabioLuporini** [comment]
A different starting point, but same conclusion as #1655 . Will patch

**Comment by FabioLuporini** [comment]
Should be fixed now
