### ISSUE TITLE
Couldn't find `libc`'s `posix_memalign` to allocate memory

### ISSUE THREAD

**Issue by closeyourmoise** [devitocodes/devito#1665]
Import python library:"from examples.seismic import Model, plot_velocity"
Modeling:"model = Model(vp=vp,             # A velocity model.
              origin=(0, 0),     # Top left corner.
              shape=(101, 101),  # Number of grid points.
              spacing=(10, 10),  # Grid spacing in m.
              nbpml=40,
             space_order=2)          # boundary layer."
RuntimeError: Couldn't find `libc`'s `posix_memalign` to allocate memory

**Comment by FabioLuporini** [comment]
on what system are you running devito?

**Comment by FabioLuporini** [comment]
is this still an issue?

**Comment by closeyourmoise** [comment]
I ran Devito after installing docker on the Windows system

**Comment by JLU-WY** [comment]
The same issue, win10 system. How to solve it?
![image](https://user-images.githubusercontent.com/72306311/127179806-a2c515a5-4be2-40df-af1d-eeb38276438b.png)
![image](https://user-images.githubusercontent.com/72306311/127180088-abd45891-a79a-48ca-8c13-422a1bfa7ae6.png)

**Comment by sks175** [comment]
I am also facing the same issue on windows10. Pls suggest solutions.

**Comment by FabioLuporini** [comment]
we do not officially support Windows. See https://github.com/devitocodes/devito/wiki/Installation-Issues#windows for alternative routes

**Comment by leomiquelutti** [comment]
Hey @closeyourmoise and @JLU-WY,

did you solve it? Same here.

**Comment by closeyourmoise** [comment]
I didn't end up with a solution. Maybe I should install a Linux VIRTUAL machine.
My solution was to buy a MacBook, ^v^.
If you can't overcome it, you might as well join them.

**Comment by mloubout** [comment]
>. Maybe I should install a Linux VIRTUAL machine.
Windows 10 has a decent linux subsystem working (WSL) that installs as a standard windows app and works quite well.

**Comment by sks175** [comment]
Hi,
I couldn't solve the problem. I installed the devito on Ubuntu and now it's
working fine.

**Comment by georgebisbas** [comment]
> Windows 10 has a decent Linux subsystem working (WSL) that installs as a standard windows app and works quite well.
Not an official solution, but this has worked in the past: https://medium.com/@soulfoodpst/install-devito-on-windows-a-tool-for-automatic-programming-3def3949e5c8

As stated earlier, 
> we do not officially support Windows. See https://github.com/devitocodes/devito/wiki/Installation-Issues#windows for alternative routes.

Closing this issue, for now, feel free to reopen, or contact in slack.
