### ISSUE TITLE
test_hoisting_scalar_divs fails if any of CC/CFLAGS/LDFLAGS/CXX are set?

### ISSUE THREAD

**Issue by tjb900** [devitocodes/devito#1739]
So I'm trying to build a local environment where the tests pass and noticed this test seems to have a problem. This is with current `master` == `02bbefb7e380d299a2508fef2923c1a4fbd5c59d`. CI doesn't seem to hit this. I suspect that none of those environment variables (CC, CFLAGS, LDFLAGS, CXX) are set in the environment, so this code path is not exercised?

I'm not sure that overriding `__new__` in this way is the neatest way to go about this?

```
__________________________________________________________________________________________________ TestAliases.test_hoisting_scalar_divs ___________________________________________________________________________________________________

self = <test_dse.TestAliases object at 0x7f66c7a63d30>

    def test_hoisting_scalar_divs(self):
        """
        Test that scalar divisions are hoisted out of the inner loops.
        """
        grid = Grid(shape=(3, 3))
    
        u = TimeFunction(name="u", grid=grid, time_order=2, space_order=4)
        m = Function(name='m', grid=grid, space_order=4)
    
        pde = m * u.dt2 - u.laplace
        eq = Eq(u.forward, solve(pde, u.forward))
    
        # Check that different backends behave the same
        op0 = Operator(eq, opt=('advanced', {'openmp': False}))
>       op1 = Operator(eq, platform='nvidiaX', language='openacc')

tests/test_dse.py:1553:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
devito/operator/operator.py:144: in __new__
    kwargs = parse_kwargs(**kwargs)
devito/operator/operator.py:972: in parse_kwargs
    configuration['compiler'].__new_from__(platform=kwargs['platform'],
devito/arch/compiler.py:192: in __new_from__
    return self.__class__(suffix=kwargs.pop('suffix', self.suffix),
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'devito.arch.compiler.CustomCompiler'>, args = (), kwargs = {'language': 'openacc', 'mpi': False, 'platform': TargetPlatform[nvidiaX], 'suffix': None}

    def __new__(cls, *args, **kwargs):
        if any(i in environ for i in ['CC', 'CXX', 'CFLAGS', 'LDFLAGS']):
>           obj = super().__new__(cls, *args, **kwargs)
E           TypeError: object.__new__() takes exactly one argument (the type to instantiate)

devito/arch/compiler.py:568: TypeError
```

**Comment by mloubout** [comment]
This looks like it's an untested corner case indeed since in all the CI the `ARCH` is set, we always have GCC/Intel/... compiler never the Custom one. The `platform='nvidiaX', language='openacc')` is tested in the gpu CI but with a preset compiler.  

Gonna assume `super()` need explicitly classes to avoid this weird behavior.  So to fix it

- Fix super()
- Add a CustomComplier CI
- Add test

**Comment by tjb900** [comment]
I _think_ in this case it's not so much a `super()` issue as because of the `*args, **kwargs` passed to `Compiler.__new__`.

`Compiler` doesn't actually override `__new__`, just `__init__`. So ultimately this means that the `__new__` is coming from `object.__new__` - and that one doesn't take any arguments (if the subclass has overridden `__new__` anyway - see opening comment of https://bugs.python.org/issue32768).

So the most economical change, which still feels a bit icky as it relies on the superclasses not overriding `__new__` to take arguments, is just either:

`super().__new__(cls)` or `Compiler.__new__(cls)`?

(have tested the second one and the issue goes away - it remains when using `Compiler.__new__(cls, *args, **kwargs)`)

**Comment by FabioLuporini** [comment]
This appears to be fixed now? (@mloubout )

**Comment by mloubout** [comment]
Yes looks fixed

**Comment by FabioLuporini** [comment]
@tjb900 closing this because it _appears_ we're good now but please do reopen if that's not the case
