### ISSUE TITLE
Integer overflow with Linearize.

### ISSUE THREAD

**Issue by Schmidt9898** [devitocodes/devito#1771]
Devito generates code that uses integer to store the mesh dimensions, and with linearize enabled at large mesh sizes this causes integer overflow in indexing.
Maybe related to #1763.

Changing these local variables type to size_t solve this problem.

Reproducing this:

DEVITO_LOGGING=DEBUG DEVITO_PLATFORM=nvidiaX DEVITO_ARCH=clang DEVITO_LANGUAGE=openmp python ./acoustic_example.py -so 8 -d 800 800 800 -opt "('advanced', {'linearize': True})"

**Comment by FabioLuporini** [comment]
Patched in #1810

**Comment by FabioLuporini** [comment]
Reopening because unsigned int may not be enough

**Comment by Schmidt9898** [comment]
In December, I had a different idea for the fix. I changed this line https://github.com/devitocodes/devito/blob/7ed661c33f0389b02892443a53f4014a66128b53/devito/symbolics/printer.py#L47 
to ' + ''.join(['[(size_t)' + self._print(x) + ']' for x in expr.indices])' .
This also solves this problem, but introduce ~6% performance drop.
