### ISSUE TITLE
Devito v3.1.0

### ISSUE THREAD

**Issue by kamranabbas20** [devitocodes/devito#1791]
I am trying to import Devito v3.1.0 package but seemingly it couldn't be found and give a "NoneType" error while importing. Is there another way to load this specific version of devito?

**Comment by mloubout** [comment]
Can you give some details on what and how you are trying to do that?

**Comment by kamranabbas20** [comment]
Sure, forgot to add the details here. So, basically first I have installed it with pip `pip install --user git+https://github.com/devitocodes/devito.git@v3.1.0` and then tried to `import devito` on VisualCode, running on Python 3.9 on Windows 10.

**Comment by mloubout** [comment]
Thank you, and do you have the stack trace of the error? 

A couple comments
- devito `v3.1.0` is from 2017 whole python 3.9 was release in 2020 so it is very likely that these version are not compatible, I would recommend to switch to python 3.6 or 3.7 for this version of devito.
- On windows, we strongly recommend to use either docker or WSL to have the underlying compilers (gcc/....) work properly for the code generation. I am not sure what VisualCode does by itself but it may lead to issues.

**Comment by kamranabbas20** [comment]
Sure, will try to downgrade Python. Here is the error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\<username>\AppData\Roaming\Python\Python39\site-packages\devito\__init__.py", line 6, in <module>
    from devito.base import *  # noqa
  File "C:\Users\<username>\AppData\Roaming\Python\Python39\site-packages\devito\base.py", line 9, in <module>
    import devito.function as function
  File "C:\Users\<username\AppData\Roaming\Python\Python39\site-packages\devito\function.py", line 8, in <module>
    from devito.memory import CMemory, first_touch
  File "C:\Users\<username>\AppData\Roaming\Python\Python39\site-packages\devito\memory.py", line 18, in <module>
    libc = ctypes.CDLL(find_library('c'))
  File "C:\Python39\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable`

**Comment by kamranabbas20** [comment]
The reason for me using `v3.1.0` is that I am trying to follow along with an SEG Tutorial on FWI and it is buggy with the latest version of devito.

**Comment by mloubout** [comment]
From the error message, it looks like you are having issues with the C libraries as expected from standard Windows, so switching to docker or WSL would be a good idea.

**Comment by mloubout** [comment]
You can also find tutorials compatible with latest devito in the examples such as in:

https://nbviewer.org/github/devitocodes/devito/tree/master/examples/seismic/tutorials/

**Comment by kamranabbas20** [comment]
Great, thanks a lot @mloubout!
