### ISSUE TITLE
Confusion with Central Finite Difference formula

### ISSUE THREAD

**Issue by CharlelieLrt** [devitocodes/devito#1799]
I am very simply trying to get the classical central difference approximation of a function: f'(x) = (f(x+h)-f(x-h))/2h + O(h²)

However, when I try:

``` python
F = Function(name="F", grid=grid, space_order=1)
F.dx.evaluate
```

I get the 1st-order forward difference formula: f'(x) = (f(x+h) - f(x))/h. The result remains the same if I change to `space_order=2`. I think the foward FD formula I get in both cases is neither centered nor of 2nd order. Is there something I am missing/misunderstanding, or is it a problem with the generation of FD formulae?

**Comment by mloubout** [comment]
The centered FD scheme is leading to checkboard artifact due to non-communicating overlapping grids shifted by one gridpoint, so by default we use an upwind FD scheme for `space-order=1`. You can however get the centered FD scheme via `F.dxc` for `space_order=2`

**Comment by FabioLuporini** [comment]
@CharlelieLrt closing as I think @mloubout provided a satisfactory answer, but feel free to reopen if u still have doubts
