### ISSUE TITLE
Running script in parallel

### ISSUE THREAD

**Issue by seaninho94** [devitocodes/devito#1802]
Hi to everyone, i'm trying to run a Python script using Devito in parallel for the first time and i really don't know if i'm using the correct commands or not. I have installed OpenMPI and did everything that is written in the Readme file (export Devito language, export devito_mpi). I was trying to use the mpirun command but if i change the number of processes value, i obtain different results from the ones that i obtain when i use only 1 process. Actually i only need to parallelize a for loop that creates a matrix, how can i do this?

Thanks a lot

**Comment by mloubout** [comment]
Could you detail the script you are running and how different the results get?

**Comment by FabioLuporini** [comment]
yes, what command line in particular. How are you exporting DEVITO_MPI?

> Actually i only need to parallelize a for loop that creates a matrix, how can i do this?

and you're trying to do this with devito? how?

**Comment by seaninho94** [comment]
I would like for now, to run in parallel several forwards for different shots. If it's possible, it will be also very useful to run in parallel several forwards with different models also. How this can be done?

**Comment by FabioLuporini** [comment]
closing because it doesn't appear to be a devito issue

**Comment by FabioLuporini** [comment]
You may want to take a look at our dask tutorials for an example of how to parallelize shots over different compute nodes

But again, "shots" or "forward modelling" aren't really devito concepts -- they're higher-level concepts
