### ISSUE TITLE
[Security] Workflow pytest-gpu.yml is using vulnerable action codecov/codecov-action

### ISSUE THREAD

**Issue by igibek** [devitocodes/devito#1812]
The workflow pytest-gpu.yml is referencing action codecov/codecov-action using references v1.0.6. However this reference is missing the commit [c6a36d2dbbf6a734e6ef75af344acdf122fcd9f9](https://github.com/codecov/codecov-action/commits/c6a36d2dbbf6a734e6ef75af344acdf122fcd9f9) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by FabioLuporini** [comment]
Thanks.

@mloubout so we should update with

```
- name: Codecov
  uses: codecov/codecov-action@v2.1.0
```

according to https://github.com/codecov/codecov-action . And not just `pytest-gpy`. Confirmed?

**Comment by mloubout** [comment]
I think so yeah
