### ISSUE TITLE
Equality of devito injections

### ISSUE THREAD

**Issue by deckerla** [devitocodes/devito#1846]
it seems like doing an equality check on two inject objects always returns true

```
import devito

shape = (11,11)
grid = devito.Grid(shape=shape)
f1 = devito.Function(name="f1", grid=grid)
u1 = devito.TimeFunction(name="u1", grid=grid)
u2 = devito.TimeFunction(name="u2", grid=grid)

q = devito.SparseTimeFunction(name="q", grid=grid, npoint=1, nt=5)
r = devito.SparseTimeFunction(name="r", grid=grid, npoint=3, nt=5)

inj1 = q.inject(field=u1.forward, expr="2*q")
inj2 = q.inject(field=u2.forward, expr="2*q")
inj3 = r.inject(field=f1, expr="r")

print(inj1 == inj2)
print(inj1 == inj3)
```

**Comment by mloubout** [comment]
What about `is`, i.e `inj1 is inj2`

**Comment by deckerla** [comment]
`is` seems to have the desired behavior.
Are there other devito objects that behave this way?  For the most part it seems like `==` functions as expected

**Comment by mloubout** [comment]
In general, `==` should be avoided for non-basic comparisons (numbers, length, ....) as it is greedier and doesn't always compare things the right way. It merely check "are this equals" not "are these two objects the same" which is slightly different.
For example `inj1 = q.inject(field=u1.forward, expr="2*q")` and `inj1b = q.inject(field=u1.forward, expr="2*q")` are `==` in every sense possible but are different object. SO `==` would always return true no matter what but `is` will not.


If you go through devito you'll see we only use `==` to compare values and strings, everything else is compared via `is` which, in addition to be more controllable and better behaved for objects, is usually faster too.

**Comment by navjotk** [comment]
Does the `is` operator work because of Sympy's object caching returning the same object?

**Comment by mloubout** [comment]
I don't think so. `is` is comparing the object itself, or if define its state (i.e https://github.com/devitocodes/devito/blob/47f81ee7d1f81ef58f2dea11c9a75ba49fe3f970/devito/finite_differences/derivative.py#L88) while `==` goes through `__eq__` if implemented.

I don't always completely get the subtle differences between the two, but as a rule of thumb `==` is more of a numeric/string comparison to avoid odd objects behaviors
