### ISSUE TITLE
The kernel 'devito (Python 3.9.7)' died

### ISSUE THREAD

**Issue by BinhKieu82** [devitocodes/devito#1856]
I got this kernel crash when running the _seismic/tutorial/14_creating_synthetics.ipynb_, at the cell as below
```
# NBVAL_SKIP
# Set up plotter
p3d = gp.plot_3d(geo_model, plotter_type='background', notebook=True)
# Plot data points and orientations
p3d.plot_data()

# Plot the surfaces
p3d.plot_surfaces()
# Plot the lithological units


p3d.plot_structured_grid('lith')
```
I run devito project through WSL1 Win10 via VSCode jupyternotebook. I've installed GDAL & downgraded numpy=1.20.3, pandas=1.3.5 to fix some minor conflicts. However, "kernel died" is a real challenge that cost me a few days.
Please see the traceback for your details, sorry for such a long log file [kernel_died.txt](https://github.com/devitocodes/devito/files/8190666/kernel_died.txt)
Hope to get you support to overcome this, thank you.

**Comment by BinhKieu82** [comment]
I got support from slack channel, thank you for that. The conflict happened once I ignite 3D plot and/or PyVista visualization. I'm not sure that crash is notorious or only my case & how to fix it.

**Comment by FabioLuporini** [comment]
uops, don't know how but I've missed this issue until today.

Glad to hear it was solved.

Closing
