### ISSUE TITLE
How to set the initial data of the TimeFunction？

### ISSUE THREAD

**Issue by Aike886** [devitocodes/devito#1886]
Once the TimeFunction defined then its initial data value is set to zero. But I want to use other initial data not zero

**Comment by mloubout** [comment]
You can either

- directly add values to it's data `u.data[0]=....` 
- Create an operator for it if the condition is fancy

You can check the CDs examples and tutorials for illustration that all use an initial condition

**Comment by Aike886** [comment]
这是来自QQ邮箱的自动回复邮件。收到！

**Comment by Aike886** [comment]
OK，I get it.Thank you very much&nbsp; !




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "devitocodes/devito"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月23日(星期三) 晚上6:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [devitocodes/devito] How to set the initial data of the TimeFunction？ (Issue #1886)





 
You can either
  
directly add values to it's data u.data[0]=....
 
Create an operator for it if the condition is fancy
  
You can check the CDs examples and tutorials for illustration that all use an initial condition

**Comment by mloubout** [comment]
For example
https://github.com/devitocodes/devito/blob/master/examples/cfd/01_convection.ipynb
