### ISSUE TITLE
Documentation Generation for the Examples directory

### ISSUE THREAD

**Issue by nimberledge** [devitocodes/devito#1933]
I have been using Devito for a while and found myself using code set up in examples/ for multiple reasons. I propose this issue so as to aid people in situations similar to mine, and also because I feel the documentation on this package is a little bit lacking. 

If someone can give me write access to the repository (or tell me if I should fork it, I'm new to contributing to open source projects), I can try to set this up

**Comment by FabioLuporini** [comment]
Hi!

Thanks, we do welcome contributions and feedback! 

Please, review our contributing guidelines: https://github.com/devitocodes/devito/blob/master/CONTRIBUTING.md
Here's the expected format for PRs, commit messages, etc: https://github.com/devitocodes/devito/wiki/Tags-for-commit-messages-and-PR-titles

Thanks!

**Comment by nimberledge** [comment]
Thanks, I will work on this

**Comment by FabioLuporini** [comment]
We'll be happy to review PRs aiming to improve the documentation. Closing this, however
