### ISSUE TITLE
Does PML support for adjoint problem?

### ISSUE THREAD

**Issue by cyanzhao42** [devitocodes/devito#1951]
Hi, thanks for the great work! I am interested in solving the FWI problem with the absorption boundary condition. I am wondering if it is available with current code base? What should I look for to get it working with FWI. I have checked the fwi.ipynb but it seems it's not absorption boundary condition there.

The code for the 3D benchmark mentioned in the [paper, figure 2](https://arxiv.org/pdf/1608.08658.pdf)would be really helpful! 

Thanks!

**Comment by mloubout** [comment]
This figure comes from using the current acoustic example operators with absorbing layer. This absorbing layer is present as well in the FWI notebook as a diffusion dampening mask `damp` in the pde

**Comment by cyanzhao42** [comment]
Got it, thanks!

**Comment by mloubout** [comment]
You can check [01_modelling.ipynb](https://nbviewer.org/github/devitocodes/devito/blob/master/examples/seismic/tutorials/01_modelling.ipynb) and    [02_rtm.ipynb](https://nbviewer.org/github/devitocodes/devito/blob/master/examples/seismic/tutorials/02_rtm.ipynb) for the implementation of the forward and adjoint used in the fwi notebook

**Comment by mloubout** [comment]
As I said, please check `01` and `02` for the definition, `03` directly uses the wrapper of these first two for simplicity.

**Comment by cyanzhao42** [comment]
gotcha! Thanks!
