### ISSUE TITLE
Update to the FAQ page

### ISSUE THREAD

**Issue by ofmla** [devitocodes/devito#1953]
@FabioLuporini I add an entry to FAQ about DEVITO_SAFE_MATH. Here's the link to my wiki page https://github.com/ofmla/devito-wiki

**Comment by ofmla** [comment]
I also added another entry with the instructions I followed in order to contribute to wiki.

**Comment by FabioLuporini** [comment]
Closing as the whole FAQ page is going to be moved to an actual GitHub repo (either Devito or the Devito website repo)
