### ISSUE TITLE
Problem with receivers' data

### ISSUE THREAD

**Issue by AMzaheri** [devitocodes/devito#1969]
Hello,

I'm trying to run a simple acoustic modeling with one source (10 m depth) and a few receivers (at 50 m depth) in a domain with shape (nz=400, nx=200), spacing = (12.5, 62.5).  
 But the shots seem to be wrong. I've attached an example of the shot records here. I was wondering if you could advise me on what could be wrong with my modeling.

I'd appreciate your help,

![shot_record_11_rec_tn1000 0_0 025f0_1src](https://user-images.githubusercontent.com/3063907/180324551-40a0817f-1707-4985-9ed9-1d3042520317.png)

**Comment by AMzaheri** [comment]
Hello georgebisbas,

Thank you for your prompt response. 
My original grid is [2000,1000, 1000]. I’m using a 2D slice of it with size of [2000,1000]. But, I first scaled the 2d slice down to .2 of the original size, and then I create the grid with
Shape = (400,200)
To keep the domain size the same as the original extent, which is 5 km depth and x= 12.5 km, I used the spacing as (12.5, 62.5).
Here is the code that I used to create the model:
scale_down = .2
scaled_Vp_down = scipy.ndimage.zoom(Vp, scale_down, order=0)

shape = (400, 200)
spacing = (12.5, 62.5)
origin = (0., 0.)

from examples.seismic import Model

model = Model(vp=scaled_Vp_down, origin=origin, shape=shape, spacing=spacing,
             space_order=2, nbl=10, bcs="damp")

from examples.seismic import TimeAxis
t0 = 0.
tn = 1000.
dt = model.critical_dt
time_range = TimeAxis(start=t0, stop=tn, step=dt)

from examples.seismic import RickerSource
f0 = 0.025
src = RickerSource(name='src', grid=model.grid, f0=f0,
                   npoint=1, time_range=time_range)

src.coordinates.data[0, :] = np.array(model.domain_size) * .5
src.coordinates.data[0, 0] = 10.


from examples.seismic import Receiver
rec = Receiver(name='rec', grid=model.grid, npoint=11, time_range=time_range)
rec.coordinates.data[:, 1] = np.linspace(0, model.domain_size[1], num=11)
rec.coordinates.data[:, 0] = 50.  # Depth is 50 m

I’m using python 3.10.4 .
Thank you very much for taking the time.
Best regards,

**Comment by georgebisbas** [comment]
Is the rest of the script shareable?
Why do you need to scale your model?

**Comment by AMzaheri** [comment]
Yes, the rest of the code is:
from devito import TimeFunction

u = TimeFunction(name="u", grid=model.grid, time_order=2, space_order=2)
pde = model.m * u.dt2 - u.laplace + model.damp * u.dt

from devito import Eq, solve
stencil = Eq(u.forward, solve(pde, u.forward))

src_term = src.inject(field=u.forward, expr=src * dt**2 / model.m)
rec_term = rec.interpolate(expr=u.forward)

from devito import Operator
op = Operator([stencil] + src_term + rec_term, subs=model.spacing_map)

op(time=time_range.num-1, dt=model.critical_dt)

plot_shotrecord_am(rec.data, model, t0, tn, f0, 100, outpath=outpath)
=======================
Shot_record_am is similar to shot_record function. I’ve only changed the order of the plot from (x,z) to (z, x).

----------------------------------------------------
def plot_shotrecord_am(rec, model, t0, tn, f0, numsrc,  outpath , colorbar=True):
    scale = np.max(rec) / 10.
    extent = [model.origin[0], model.origin[0] + 1e-3*model.domain_size[1],
              1e-3*tn, t0]
    plt.figure(figsize=(8, 6),dpi=80)

    plot = plt.imshow(rec, vmin=-scale, vmax=scale, cmap=cm.gray, extent=extent)  

    plt.xlabel('X position (km)')
    plt.ylabel('Time (s)')

    # Create aligned colorbar on the right
    # The divider causes bad aspect ratio
    if colorbar:
        plt.colorbar(plot)
        ax = plt.gca()

ratio = 1.8
    x_left, x_right = ax.get_xlim()
    y_left, y_right = ax.get_ylim()
    ax.set_aspect(abs((x_left - x_right)/(y_left - y_right))*ratio)

   # plt.show()
    plt.savefig(os.path.join(outpath, \
               'shot_record_%s_rec_tn%s_%sf0_%ssrc.png'% (rec.shape[1], tn, f0, numsrc)))
I scaled it down only for this example, as it was time consuming to run on the main grid even for a simple geometry. But I will try the original grid, and will let you know of the result.

Thank you.

**Comment by AMzaheri** [comment]
Hello,

I tried it on the original grid with size [2000,1000]. But, the shot record is the same., unfortunately.

**Comment by mloubout** [comment]
> which is 5 km depth and x= 12.5 km, I used the spacing as (12.5, 62.5).

That doesn't seem right. With a 401x201 grid that should be 31.25m by 25m.

25Hz source is extremely high for such a coarse grid as well and very low space order. It's gonna be very very dispersive

**Comment by AMzaheri** [comment]
Thank you.
The depth is 5000 m, and hence extent = spacing * shape should be 5000 m in depth by 12.5 km in X.
With 401x201 grid and 31.25m by 25m, depth = 12.5 km, and X = 5 km, which is not correct. As you can see in the attached image, which is with the suggested grid, the X position is 5 km rather than 12.5 km.

As for the peak frequency, I have tested a wide range of frequencies, but shot records are somehow similar. For lower frequencies the white and black bulbs are observed longer though. The larger the frequency is the smaller black and white bulbs become. The picture was made with the same grid shape and spacing suggested by mloubout  and f0=0.001.

Could it be due the order of the axes of the grid, which is [z = 2000, x= 1000], rather than (x, z)? Is devito sensitive to the order of the axes?

Thank you.
![shot_record_11_rec_tn1000 0_0 001f0_1src](https://user-images.githubusercontent.com/3063907/180616678-0b7d1eb1-1e7e-4bb3-b95c-d0d527590565.png)
