### ISSUE TITLE
Values of the second derivative of a TimeFunction

### ISSUE THREAD

**Issue by AMzaheri** [devitocodes/devito#1993]
I’ve been trying to calculate the second derivative of a TimeFunction as follows:

Image1 = TimeFunction(name='image', grid=model.grid, space_order=2)
op = Operator(Eq(image1, image1.dx2))
op.apply(time=0)
Could someone tell me if I’m right please? If so, I was wondering how I can have access to the values of the second derivative. 

Thank you,

**Comment by FabioLuporini** [comment]
you can't assign it to `image1` or you will override the input while you're still computing the second derivative. The output should therefore be another objection, not `image1`
