### ISSUE TITLE
How can I save the wavefield and set the boundary conditions at the same time?

### ISSUE THREAD

**Issue by z981201** [devitocodes/devito#2024]
I'm a beginner for Devito, and when I study the introduction `\devito\examples\seismic\abc_methods,` I want to save the wavefield, 
so change
`u = TimeFunction(name="u",grid=grid,time_order=2,space_order=2,staggered=NODE,dtype=np.float64)`
to 
`u = TimeFunction(name="u",grid=grid,time_order=2,space_order=2,staggered=NODE,dtype=np.float64,save=time_range.num)`.
But there is an error after executing the following code `op(time=nt-2,dt=dt0)`. What's the problem?
[error.txt](https://github.com/devitocodes/devito/files/9844024/error.txt)

**Comment by mloubout** [comment]
From the error file it looks like it failed to compile, would you have the compilation error itself?
