### ISSUE TITLE
edit update = vp + alpha * dm

### ISSUE THREAD

**Issue by vahid-honarbakhsh** [devitocodes/devito#2077]
Hello
I have made the following changes in the code:

lamda = 0.01
update = vp + alpha * dm + (alpha* lamda* vp_grad)

also vp_grad is a numpy matrix.
But it gives an error:

ValueError                                Traceback (most recent call last)
[<ipython-input-73-9cd36e6c33cb>](https://localhost:8080/#) in <module>
     34 
     35     # Update the model estimate and enforce minimum/maximum values
---> 36         update_with_box(model0.vp, alpha, direction, vp_grad)
     37 
     38     # Log the progress made

4 frames
[/usr/local/lib/python3.8/dist-packages/devito/finite_differences/differentiable.py](https://localhost:8080/#) in <listcomp>(.0)
    404 
    405         # a+0 -> a
--> 406         args = [i for i in args if i != 0]
    407 
    408         # Reorder for homogeneity with pure SymPy types

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

How can I resolve this error?

**Comment by jiwei08** [comment]
Maybe it is a Numpy error and could you show me which part of codes causes this error?

**Comment by mloubout** [comment]
Could you show the actually code change, i.e the whole cell as a code snipet

**Comment by vahid-honarbakhsh** [comment]
Hi, 
I was able to fix the problem.
I took the derivative from the regularizer and added it to direction:
direction.data[:] =  direction.data[:] + (lamda * vp_grad)

thanks
