### ISSUE TITLE
Old notebooks not running: help needed

### ISSUE THREAD

**Issue by rsarkar-github** [devitocodes/devito#2091]
[2023_Devito_Issue.zip](https://github.com/devitocodes/devito/files/11009962/2023_Devito_Issue.zip)

Hi All,

I would like to have some help on some Devito code that I wrote in 2020. Unfortunately, after installing the most recent version of Devito from pypi, the same notebook does not run completely. I have attached a .html, and a .ipynb version of the notebook that is failing. 

Can someone help me track down the error, or how I should update my old code? I code is performing "time dependent" Born modeling, and is quite simple, so a Devito expert should be able to catch what needs to be done quite quickly and tell me (I hope).

Best,
Rahul

**Comment by mloubout** [comment]
When you define 
`dt = Constant('dt')` in your born operator you are creating a Constant for an already existing one `model.grid.time_dim.spacing` so it creates conflicting variables in the generated code, so I would recommend to remove that and use the `grid` spacing one instead (so one line change) and it works. fine

**Comment by rsarkar-github** [comment]
Great! Thanks, it works.
