### ISSUE TITLE
Remove dependency on codecov in requirements.txt

### ISSUE THREAD

**Issue by dsleiter** [devitocodes/devito#2103]
The codecov team removed the python package from pypi:
* https://about.codecov.io/blog/message-regarding-the-pypi-package/
* https://community.codecov.com/t/codecov-yanked-from-pypi-all-versions/4259/11

This breaks devito's CI, as well as the CI of any project which depends on devito.
Example: https://github.com/devitocodes/devito/actions/runs/4597919288/jobs/8165744602?pr=2095

It looks devito is already using the codecov-action github workflow. Is the dependency on `codecov` in `requirements.txt` needed any more?

**Comment by dsleiter** [comment]
Looks like this was resolved in [v4.8.1](https://github.com/devitocodes/devito/releases/tag/v4.8.1) (in [64dda43](https://github.com/devitocodes/devito/commit/64dda4398f62eb33f655458a0b76bd3a2990ace7)). Thanks @FabioLuporini!

**Comment by FabioLuporini** [comment]
no probs 👍
