### ISSUE TITLE
Error on ppc from gcc flag `march=native`

### ISSUE THREAD

**Issue by raminammour** [devitocodes/devito#2146]
Hello, 

I am getting this error on ppc:
`gcc -O3 -g -fPIC -Wall -std=c99 -march=native -Wno-unused-result -Wno-unused-variable -Wno-unused-but-set-variable -ffast-math -shared -fopenmp /tmp/devito-jitcache-uid280401/6ac5bd02be57b403f27b5b27c9ab6c7404ea091c.c -lm -o /tmp/devito-jitcache-uid280401/6ac5bd02be57b403f27b5b27c9ab6c7404ea091c.so`
gcc: error: unrecognized command line option ‘-march=native’; did you mean ‘-mcpu=native’?

It looks like this is common (Switch between -march=native (x86) and -mcpu=native -mtune=native (PowerPC) ) and here is an example of how it is solved elsewhere, if it helps :)

https://github.com/mfem/mfem/pull/219

Cheers!

**Comment by FabioLuporini** [comment]
Ah, we do that with Clang but not with GCC:

https://github.com/devitocodes/devito/blob/master/devito/arch/compiler.py#L468-L470

Would you like to contribute a PR to fix this? patch goes around here:

https://github.com/devitocodes/devito/blob/master/devito/arch/compiler.py#L398

It's just a minor change, and should you decided to proceed, take a look here: https://github.com/devitocodes/devito/blob/master/CONTRIBUTING.md#making-changes

Thanks!

**Comment by raminammour** [comment]
I submitted a PR, should not be too intrusive. I guess you are not testing on ppc regularly?

**Comment by FabioLuporini** [comment]
Thanks a lot! Commented in PR, looking good

> I guess you are not testing on ppc regularly?

We don't!  I genuinely thought they weren't even around anymore :) Can I ask how/why you're finding yourself running on ppc?

**Comment by raminammour** [comment]
I have the chagrin of dealing with an in-house ppc hpc system (I guess the other one still standing is SUMMIT). Devito is not the only code to drop support or support ppc at a lower tier, it is painful :)
