### ISSUE TITLE
icc needs to be updated to icx

### ISSUE THREAD

**Issue by ggorman** [devitocodes/devito#2153]
icc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.

**Comment by mloubout** [comment]
See #2051 it is now supported, just need to run the ICC image with `-e DEVITO_ARCH=icx`
