### ISSUE TITLE
is the SYCL language option functional?

### ISSUE THREAD

**Issue by MarkCheeseman** [devitocodes/devito#2239]
I am trying to run a Devito benchmark (eg. **devito/benchmarks/user/benchmark.py**) on an Intel Data Center MAX 1100 GPU using SYCL.  There seems to be language support for SYCL in **devito/arch/compiler.py**.   I have modified the **_get_gpu_info_** function in devito/arch/archinfo.py so that the relevant system information such as memory used, product and vendor is defined.

I am running the benchmark as so:
unset DEVITO_LOGGING
export DEVITO_ARCH=icx DEVITO_PLATFORM=intelgpuX DEVITO_LANGUAGE=sycl
python3 devito/benchmarks/user/benchmark.py run -P tti -d 256 256 256 -so 12 -t 10

I am using a virtual environment with Python 3.9.7 from Intel Composer v2022.1.0.  Devito support is built by running pip install inside a clone of the github repository.  The error I get when I try running the benchmark is attached.  I am unsure if I am calling the benchmark incorrectly or if the SYCL / intelgpuX implementations needs to be modified.

Any feedback / suggestions would be most welcome.
[error_output.txt](https://github.com/devitocodes/devito/files/12974586/error_output.txt)

**Comment by FabioLuporini** [comment]
SYCL is being actively developed but it's part of DevitoPRO
