### ISSUE TITLE
Amplitude of the damping term

### ISSUE THREAD

**Issue by jiwei08** [devitocodes/devito#2267]
I'm trying to solve the wave equation in $\mathbb{R}^2$ and use the abc methods which add a damping term to the original equation. The amplitude of the damping term is related to the maximum of the velocity $v_{max}$, namely a scaling factor $1/v_{max}$, as shown in the [notebook](https://github.com/devitocodes/devito/blob/master/examples/seismic/abc_methods/02_damping.ipynb). But the function `initialize_damp()` in `examples/seismic/model.py` seems to omit it, which would lead to the wrong solution for the case that $c$ is much larger or smaller than $1$.

Any feedback would be appreciated.

**Comment by mloubout** [comment]
The examples are a set of illustrative examples and are indeed not fully generic, so there are some cases that are outside the scope of those examples that might not work perfectly. But the examples should give a good didactic base to develop your own propagators.
