### ISSUE TITLE
Rebuilding a `ConditionalDimension` with no factor adds a factor.

### ISSUE THREAD

**Issue by EdCaunt** [devitocodes/devito#2325]
If a `ConditionalDimension` is created with `factor=None`, then `self._factor` is set to `None`, but `self.factor` will return 1. As such, when rebuilding a `ConditionalDimension` with no factor, a factor of 1 is added unexpectedly, changing the generated code.

**Comment by georgebisbas** [comment]
Is there an MFE for this?

**Comment by EdCaunt** [comment]
Create a `ConditionalDimension` with a condition but no factor, then compare `cd._factor` to `cd._rebuild()._factor`
