### ISSUE TITLE
add noise 

### ISSUE THREAD

**Issue by vahid-honarbakhsh** [devitocodes/devito#2355]
Hi,

I want to add  random noise to the data. How can I do it?

# Generate synthetic data from true model
  _, _, _ = solver.forward(vp=model.vp, rec=d_obs) + noise

Thanks,
vahid

**Comment by mloubout** [comment]
```
rec, u, summary = solver.forward(vp=model.vp, rec=d_obs) 
rec.data[:] += noise_you_want # of shape rec.shape
```

**Comment by georgebisbas** [comment]
@vahid-honarbakhsh is that still an issue?
Since this is mostly a question on how to use the DSL and not a repository-specific issue,
I am closing this for now and you can always ask in our slack channel: https://join.slack.com/t/devitocodes/shared_invite/zt-gtd2yxj9-Y31YKk_7lr9AwfXeL2iMFg
