### ISSUE TITLE
Slack Link

### ISSUE THREAD

**Issue by scott314159** [devitocodes/devito#2371]
Sorry if this does not belong here -- it seems that the slack link in the "contact us" section has expired.  When I click on it I get a page that says:  "This link is no longer active"

**Comment by FabioLuporini** [comment]
could you try now?

**Comment by scott314159** [comment]
It did not work.  The link I clicked on is:  https://join.slack.com/t/devitocodes/shared_invite/zt-gtd2yxj9-Y31YKk_7lr9AwfXeL2iMFg
The page I was on is:  https://www.devitoproject.org/contact.html

I also tried the link on:  https://www.devitoproject.org/contact.html and it did not work there either.

**Comment by mloubout** [comment]
Some leftover expired slack links were still on the website. All the links should not be updated to the current working one

https://join.slack.com/t/devitocodes/shared_invite/zt-2hgp6891e-jQDcepOWPQwxL5JJegYKSA

**Comment by scott314159** [comment]
Thank you.  It works now.
