### ISSUE TITLE
Pull repeating code from tutorials into a utility module.

### ISSUE THREAD

**Issue by ggorman** [devitocodes/devito#405]
There is a lot of code repetition currently in the seismic tutorials. Code needs re-engineering and pulling out into utility module so it can be imported instead.

**Comment by FabioLuporini** [comment]
I haven't checked the notebooks in #525 yet: is this being done there @ggorman ?

**Comment by FabioLuporini** [comment]
I think this can be closed. Feel free to reopen if you think I'm wrong @mloubout
