### ISSUE TITLE
notebook describing BC setup

### ISSUE THREAD

**Issue by FabioLuporini** [devitocodes/devito#606]
from trivial ones (eg Dirichlet) to more fancy ones (eg Higdon BCs, as defined in ``tests/test_dimension.py``

**Comment by georgebisbas** [comment]
Just noting that until now, Dirichlet BCs are mentioned already in in a way:
1) [01_modelling.ipynb ](https://github.com/opesci/devito/blob/8b94d5c666102e4d3abd8cc0590699c6dd452d21/examples/seismic/tutorials/01_modelling.ipynb)
2) [04_burgers.ipynb
](https://github.com/opesci/devito/blob/efe655cb12475e1dad3db913638f1c9a68b638fc/examples/cfd/04_burgers.ipynb)
3) [06_poisson.ipynb](https://github.com/opesci/devito/blob/05e571b8e970d3f32ffe4977511145d20b926019/examples/cfd/06_poisson.ipynb)

**Comment by georgebisbas** [comment]
To be started tomorrow at least about Dirichlet and Neumann.

**Comment by FabioLuporini** [comment]
@rhodrin the smoother we envisaged might be used for this notebook too

**Comment by ggorman** [comment]
This needs to replace damping field with subdomain support for BC's in examples and tutorials.

**Comment by FabioLuporini** [comment]
@mloubout @rhodrin @EdCaunt can we close this once #1117 is in, or should we wait for more material?

**Comment by EdCaunt** [comment]
I think it can probably be closed? 1117 details free surface (so both Dirichlet and Neumann are demonstrated) and PML using subdomains. Once I finish 1117, I was planning on a second notebook with CPMLs too.

**Comment by FabioLuporini** [comment]
perfect, closing this
