### ISSUE TITLE
purge conftest.py

### ISSUE THREAD

**Issue by FabioLuporini** [devitocodes/devito#764]
Symbols/Functions/... should be created directly within the tests using them, or at most as ``pytest.fixture`` within the relevant python modules (e.g., in ``test_operator.py``). IOW, things such as ``t0, t1, t2, ...`` but also ``unit_box``  or ``iters``, should be entirely removed/moved

**Comment by ggorman** [comment]
Migrating comment from #634:

the pytest_fixture a is defined at least twice: once in conftest.py and then again in interpolation.py. Depending on the execution order of the tests, this may lead to "false bugs".
This really sucks. It's a mistake to pollute conftest.py with lots of symbols/dimensions/... to be shared by different tests. It also sucks that pytest registers two fixtures with the same name and doesn't complain

**Comment by mloubout** [comment]
#1042

**Comment by FabioLuporini** [comment]
@mloubout I think we can close this now?

**Comment by FabioLuporini** [comment]
ah no sorry, waiting for 1042. Almost!

**Comment by mloubout** [comment]
Done , closing
