### ISSUE TITLE
misc website fixes

### ISSUE THREAD

**Issue by ggorman** [devitocodes/devito#818]
* update papers/talks 
  * ~~note: Rice talk is now online: http://rice2019oghpc.rice.edu/program/~~ website broken
  * Links should include open access/preprint versions.
* documentation should live at www.devitoproject.org/…, not at www.opesci.org/…
* ~~move “citing” to separate tab~~ Done
* ~~change link to installation instructions~~ Done
* ~~replace HORRIBLE BANNER~~ Done
* ~~link to right twitter page (@DevitoCodes; kill obsolete @OpesciProject ?)~~ Done
* ~~TYPO contributers/contributors~~ Done

**Comment by FabioLuporini** [comment]
some updates to the publications list have just been made by @philippwitte and @mloubout . Thanks!

**Comment by FabioLuporini** [comment]
in fact, the Rice talk does look online: http://rice2019oghpc.rice.edu/program/
I can access it [here](https://static.sched.com/hosted_files/2019riceoilgasconference/96/1%20Gorman.pdf)

**Comment by btrb** [comment]
it looks good!
