### ISSUE TITLE
document environment variables

### ISSUE THREAD

**Issue by FabioLuporini** [devitocodes/devito#841]
We need a document describing what the supported environment variables are (`print_defaults` ...) and what they do

for example:

DEVITO_DEBUG_COMPILER: writes to standard output the command line used to jit-compile an operator (eg `gcc ... -O3 ...`
DEVITO_JIT_BACKDOOR: escape hatch for custom kernels. The typical use case is as follows: one runs a Devito program; then, once the session is over, the generated file(s) is(are) modified manually (e.g., for debugging or for performance experimentation); finally, when re-running the same program, if DEVITO_JIT_BACKDOOR is set, Devito won't overwrite the user-modified files, but rather it will compile and call them (thus it's pretty much like bypassing code generation) 
DEVITO_FIRST_TOUCH: first touch upon data allocation. Works around numa issue (though this is a fake issue thanks to MPI) and allows parallel initialisation by multiple threads

**Comment by georgebisbas** [comment]
Should that be a typical document, or like a cheatsheet-poster ?

**Comment by FabioLuporini** [comment]
Closing as now the wiki page is updated with all env vars
