### ISSUE TITLE
Replace NBVAL_IGNORE_OUTPUT in examples with a cell tag

### ISSUE THREAD

**Issue by FabioLuporini** [devitocodes/devito#858]
see https://nbval.readthedocs.io/en/latest/#Using-tags-instead-of-comments

**Comment by FabioLuporini** [comment]
I've started with this commit: ece3c82c47d586a6b7dc6bb9f1ce2f6f39c8697d

it's trivial

**Comment by navjotk** [comment]
I'm not sold on the why here. With the comments approach, the testing "workflow" is more obviously visible - you can immediately tell which cells are being tested. What is the advantage of hiding that?

**Comment by FabioLuporini** [comment]
less pollution

**Comment by navjotk** [comment]
I disagree. [Explicit is better than implicit](https://www.python.org/dev/peps/pep-0020/)

**Comment by FabioLuporini** [comment]
our notebooks are for users, not for developers, so I think I still prefer tags

either way, nitpicking. I don't mind sticking to the comments if that's what everybody prefers (though this issue has been ignored for 8 months)

**Comment by FabioLuporini** [comment]
there's no unanimous consensus on this, so I'm closing the issue
