### ISSUE TITLE
YASK, symbolic caching, and clear_cache

### ISSUE THREAD

**Issue by FabioLuporini** [devitocodes/devito#944]
When running with the YASK backend, the following fails:

```
from devito import Grid, TimeFunction, Eq, Operator, clear_cache

grid = Grid(shape=(4, 4, 4)) 
x, _, _ = grid.dimensions

u = TimeFunction(name='u', grid=grid)

a = u.forward.subs(x, 1)

u.data[:] = 1.0 

clear_cache(dump_contexts=False)

u.data[1]
```

`u`'s `__del__` gets called, somewhat, due to the call to `subs` . This is somewhat due to sympy caching, which caches operations, not objects, including `subs`.

**Comment by mloubout** [comment]
closing?

**Comment by mloubout** [comment]
Yask not supported anymore, closing.
