### ISSUE TITLE
Autotuning breaks on Windows

### ISSUE THREAD

**Issue by chiefenne** [devitocodes/devito#962]
Hi,
I'd like to use devito on Windows 10. In autotuning.py a Unix only module (resource) is imported, which breaks it running on Windows.
I have Anaconda Python installed and run a dedicated devito environment. 
Any suggestions?

**Comment by FabioLuporini** [comment]
Hi,

I'd accept a patch that changes [this line](https://github.com/opesci/devito/blob/master/devito/core/autotuning.py#L364)

to something along the lines of

```
try:
     import resource
     options['stack_limit'] = resource.getrlimit(resource.RLIMIT_STACK)[0] / 4
except ImportError:
     warning(...)
     options['stack_limit'] = <some sensible values> (2 MB? 1MB?)
```

Any other alternative to obtaining the RLIMIT_STACK would be welcome

Thanks for pointing this out!

**Comment by chiefenne** [comment]
Hi,
thank you this would be good.
Though I have no clue what would be a meaningful default.

**Comment by FabioLuporini** [comment]
[here] it says 1 MB, so perhaps 0.75 ? with a brief comment explaining why

**Comment by FabioLuporini** [comment]
We don't (and likely we never will) support pure Conda on Windows. However, to run on Windows, we recommend one of the three approaches here: https://github.com/devitocodes/devito/wiki/Installation-Issues#windows

Definitely WSL doesn't have the issue documented here, hence closing.
