### ISSUE TITLE
`opt` parameter  lacks documentation

### ISSUE THREAD

**Issue by rhodrin** [devitocodes/devito#976]
Currently the `mode` parameter accepted by the DLE has undocumented behavior: it accepts certain documented strings but also accepts tuples of 'sub modes' which aren't well documented.

`mode` should (probably) be re-worked as a `class` and its usage properly documented.

**Comment by georgebisbas** [comment]
Should that be closed after moving to `opt` ?

**Comment by FabioLuporini** [comment]
renamed the issue as now what we need is documentation for `opt`

**Comment by FabioLuporini** [comment]
Closing as now `opt` is documented inside `/examples/performance/00_overview.ipynb`
