### ISSUE TITLE
String formating

### ISSUE THREAD

**Issue by mloubout** [devitocodes/devito#980]
Should we move to the current newish standard of `"blabla {..}".format` for strings?

Just opening the discussion that's alll, I understand maybe a pain to do so can ignore it.

**Comment by FabioLuporini** [comment]
ideally yes, the only reason I didn't do it is that it's a pain

for homogeneity, I think we should stick to the current format everywhere?

**Comment by mloubout** [comment]
Closing as no real issue, will consider if someone wants to reformate all strings.
