### ISSUE TITLE
Sympy standard function with our types

### ISSUE THREAD

**Issue by mloubout** [devitocodes/devito#984]
So basically the issue is that all of sympy standard functions ignore our type or transform into their own

For example `sqrt(u)` is a `sympy.Pow` while we would want a `Differentiable.Pow`. I am unsure how to proceed about this, most of the ideas I would require to import everything in Devito and add our own version and would break the moment someone uses a function we didn;t think of (there is like 100 in sympy so not gonna redo everything)

Open to suggestions

**Comment by FabioLuporini** [comment]
I think the only possibility is to import them all and subclass them such that they get a different __new__ just like Add, Mul, ...

I don't think it's bad, it's just a little tedious but it shouldn't take an insane amount of time...

I'd add all nonlinear functions here: https://fenicsproject.org/docs/ufl/1.4.0/ufl.html#id2

it's roughly more than 20, so it's doable

**Comment by mloubout** [comment]
Yes it is just tidious I don't mind that way just takes time

**Comment by btrb** [comment]
# sympy/sympy/functions/elementary/miscellaneous.py
- Max
class: #642
- Min
class: #760
- sqrt
function: #60

## sympy/sympy/functions/elementary/complexes.py
- abs
class: #400
- sign
class: #246

## sympy/functions/elementary/exponential.py
- exp
class: #190
- ln

## sympy/functions/special/error_functions.py
- erf
class: #44

## sympy/functions/elementary/trigonometric.py
- cos
class: #495
- sin
class: #203
- tan
class: #931
- acos
class: #2206
- asin
class: #2039
- atan
class: #2379
- atan_2
class: #2976

## sympy/functions/elementary/hyperbolic.py
- cosh
class: #264
- sinh
class: #69
- tanh
class: #432

**Comment by FabioLuporini** [comment]
@btrb would you like to give this a go? as a simple self-contained exercise?

**Comment by btrb** [comment]
oh, yes. sure! although i don't quite have a clear picture of a solution 
one thing that crossed my mind, let's say for `Max`, was to:
declare a new class in `differentiable.py`:
```
class Max(sympy.Max, DifferentiableOp):
    __new__ = DifferentiableOp.__new__
```
add it to `class diffiffy`, like: 
```
    @_cls.register(sympy.Max)
    def _(obj):
        return Max
```
add the corresponding decorator to `diffify._()`:
```
@_cls.register(Max)
```
then include
```
evalf_table[Max] = evalf_table[sympy.Max]
```
and finally override the sympy operator in `Differentiable` with
``` 
    def __max__(self, other):
        return Max(self, other)
```

i'm aware that it should not be that trivial though

**Comment by mloubout** [comment]
I would avoid to go through diffify too much and clutter it with too much stuff. Most of these are `sympy.Function` so there should be a way to go through our own `basic` to make it nicely and avoid too much code.

**Comment by mloubout** [comment]
This "update" would also be a good time to enforce types on these functions in the generated code (cos/cosf, sin/sinf,....) as we currently have the double precisions ones (cos, sin,...) always (unless I missed something)

**Comment by mloubout** [comment]
Started in #1549 , not all of it though, will need to add the other ones the same way.
